import uuid
import enum
from datetime import datetime
from sqlalchemy import (
    Column, String, Text, Numeric, Integer, Boolean,
    ForeignKey, Enum, Date, DateTime, JSON,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.db.base import Base, TimestampMixin


class AIRequestStatus(str, enum.Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class AIRequestType(str, enum.Enum):
    PREDICTION = "PREDICTION"
    RECOMMENDATION = "RECOMMENDATION"
    SCENARIO = "SCENARIO"
    FORMULATION = "FORMULATION"
    DOCUMENT = "DOCUMENT"


class AIProvider(str, enum.Enum):
    ANTHROPIC = "anthropic"
    OPENAI = "openai"
    GEMINI = "gemini"
    MOCK = "mock"
    AUTO = "auto"


class AIRequest(Base, TimestampMixin):
    """Log of every AI call — for audit, cost tracking, and retry."""
    __tablename__ = "ai_requests"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    request_type = Column(Enum(AIRequestType), nullable=False)
    provider = Column(Enum(AIProvider), nullable=False, default=AIProvider.ANTHROPIC)
    model = Column(String(100), nullable=True)
    status = Column(Enum(AIRequestStatus), nullable=False, default=AIRequestStatus.PENDING)
    prompt_tokens = Column(Integer, nullable=True)
    completion_tokens = Column(Integer, nullable=True)
    latency_ms = Column(Integer, nullable=True)
    error_message = Column(Text, nullable=True)
    input_data = Column(JSON, nullable=True)        # what was sent to AI
    output_data = Column(JSON, nullable=True)       # raw AI response
    created_by_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)

    created_by = relationship("User")


class AIPrediction(Base, TimestampMixin):
    """Stored prediction result."""
    __tablename__ = "ai_predictions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    request_id = Column(UUID(as_uuid=True), ForeignKey("ai_requests.id", ondelete="SET NULL"), nullable=True)
    prediction_type = Column(String(50), nullable=False)   # sales_forecast | demand | stock_depletion | cost_trend | supplier_risk
    subject_id = Column(UUID(as_uuid=True), nullable=True)  # product_id / supplier_id / etc.
    subject_name = Column(String(255), nullable=True)
    period = Column(String(20), nullable=True)              # "2026-05" or "next_30_days"
    forecast_value = Column(Numeric(18, 4), nullable=True)
    confidence_score = Column(Numeric(5, 4), nullable=True)   # 0.0 – 1.0
    risk_level = Column(String(20), nullable=True)          # low | medium | high | critical
    trend = Column(String(20), nullable=True)               # up | down | stable
    summary = Column(Text, nullable=True)
    details = Column(JSON, nullable=True)                   # full structured output
    is_archived = Column(Boolean, default=False, nullable=False)
    created_by_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)

    request = relationship("AIRequest")
    created_by = relationship("User")


class AIRecommendation(Base, TimestampMixin):
    """Stored recommendation."""
    __tablename__ = "ai_recommendations"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    request_id = Column(UUID(as_uuid=True), ForeignKey("ai_requests.id", ondelete="SET NULL"), nullable=True)
    category = Column(String(50), nullable=False)   # pricing | stock | supplier | production | margin
    title = Column(String(255), nullable=False)
    reason = Column(Text, nullable=True)
    expected_impact = Column(Text, nullable=True)
    confidence_level = Column(String(20), nullable=True)   # low | medium | high
    priority = Column(String(20), nullable=True)           # low | medium | high | critical
    action_data = Column(JSON, nullable=True)              # structured action details
    is_actioned = Column(Boolean, default=False, nullable=False)
    is_dismissed = Column(Boolean, default=False, nullable=False)
    created_by_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)

    request = relationship("AIRequest")
    created_by = relationship("User")


class AIFormulation(Base, TimestampMixin):
    """Stored chemical formulation generated by AI."""
    __tablename__ = "ai_formulations"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    request_id = Column(UUID(as_uuid=True), ForeignKey("ai_requests.id", ondelete="SET NULL"), nullable=True)
    name = Column(String(255), nullable=False)
    product_category = Column(String(100), nullable=False)
    version = Column(String(50), nullable=False, default="standard")  # standard | low_cost | premium | eco
    target_properties = Column(JSON, nullable=True)
    cost_target = Column(Numeric(14, 4), nullable=True)
    performance_priority = Column(String(20), nullable=True)   # cost | balanced | quality
    # Full AI output
    formulation_data = Column(JSON, nullable=False)            # complete structured formulation
    estimated_cost_per_kg = Column(Numeric(14, 4), nullable=True)
    # Metadata
    is_approved = Column(Boolean, default=False, nullable=False)
    is_favorite = Column(Boolean, default=False, nullable=False)
    notes = Column(Text, nullable=True)
    created_by_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)

    request = relationship("AIRequest")
    created_by = relationship("User")


class AIScenario(Base, TimestampMixin):
    """Stored scenario simulation."""
    __tablename__ = "ai_scenarios"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    request_id = Column(UUID(as_uuid=True), ForeignKey("ai_requests.id", ondelete="SET NULL"), nullable=True)
    title = Column(String(255), nullable=False)
    scenario_type = Column(String(50), nullable=False)   # price_change | product_change | cost_change | supplier_change
    input_parameters = Column(JSON, nullable=True)
    expected_impact = Column(Text, nullable=True)
    risks = Column(JSON, nullable=True)
    opportunities = Column(JSON, nullable=True)
    simulation_data = Column(JSON, nullable=False)
    created_by_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)

    request = relationship("AIRequest")
    created_by = relationship("User")


# ── Gap 66: Natural Language ERP Control ─────────────────────────────────────

class NLCommandStatus(str, enum.Enum):
    PENDING_CONFIRMATION = "PENDING_CONFIRMATION"
    CONFIRMED = "CONFIRMED"
    EXECUTED = "EXECUTED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"


class NLCommandLog(Base, TimestampMixin):
    """
    Log of natural language commands parsed and (optionally) executed.
    Commands go through: parse → confirm → execute.
    """
    __tablename__ = "ai_nl_commands"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(String(100), nullable=True, index=True)
    user_name = Column(String(200), nullable=True)

    command_text = Column(Text, nullable=False)
    parsed_intent = Column(String(200), nullable=True)
    parsed_action = Column(Text, nullable=True)
    target_endpoint = Column(String(300), nullable=True)
    params_json = Column(JSON, nullable=True)
    requires_confirmation = Column(Boolean, default=True, nullable=False)
    risk_level = Column(String(20), default="MEDIUM", nullable=False)

    status = Column(Enum(NLCommandStatus), nullable=False, default=NLCommandStatus.PENDING_CONFIRMATION)
    confirmed_by = Column(String(200), nullable=True)
    confirmed_at = Column(DateTime, nullable=True)
    result_summary = Column(Text, nullable=True)
    error_message = Column(Text, nullable=True)
    executed_at = Column(DateTime, nullable=True)


# ── Gap 67: AI Agent Governance Framework ────────────────────────────────────

class AIAgentPolicy(Base, TimestampMixin):
    """Governance policy defining what an AI agent is allowed to do."""
    __tablename__ = "ai_agent_policies"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    agent_name = Column(String(200), nullable=False, unique=True, index=True)
    description = Column(Text, nullable=True)
    allowed_actions = Column(JSON, nullable=True)           # list of permitted action codes
    forbidden_actions = Column(JSON, nullable=True)         # explicit deny list
    max_cost_per_run_tokens = Column(Integer, nullable=True)  # token budget per run
    requires_human_approval = Column(Boolean, default=True, nullable=False)
    max_runs_per_hour = Column(Integer, nullable=True)
    allowed_modules = Column(JSON, nullable=True)           # e.g. ["sales", "inventory"]
    hallucination_guardrail = Column(Boolean, default=True, nullable=False)
    rag_enabled = Column(Boolean, default=False, nullable=False)
    is_active = Column(Boolean, default=True, nullable=False)
    created_by = Column(String(200), nullable=True)
    notes = Column(Text, nullable=True)


class AIAgentRunStatus(str, enum.Enum):
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"     # blocked by governance policy
    FLAGGED = "FLAGGED"     # anomalous behaviour detected


class AIAgentRun(Base, TimestampMixin):
    """Audit log of every AI agent execution."""
    __tablename__ = "ai_agent_runs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    policy_id = Column(UUID(as_uuid=True), ForeignKey("ai_agent_policies.id", ondelete="SET NULL"), nullable=True, index=True)
    agent_name = Column(String(200), nullable=False, index=True)
    trigger = Column(String(200), nullable=True)             # user_request | scheduled | webhook
    triggered_by = Column(String(200), nullable=True)
    actions_taken = Column(JSON, nullable=True)              # list of actions performed
    tokens_used = Column(Integer, nullable=True)
    cost_usd = Column(Numeric(10, 6), nullable=True)
    human_approved = Column(Boolean, nullable=True)
    approved_by = Column(String(200), nullable=True)
    status = Column(Enum(AIAgentRunStatus), nullable=False, default=AIAgentRunStatus.STARTED)
    result_summary = Column(Text, nullable=True)
    anomaly_flag = Column(Boolean, default=False, nullable=False)
    anomaly_reason = Column(Text, nullable=True)
    started_at = Column(DateTime, default=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)

    policy = relationship("AIAgentPolicy", foreign_keys=[policy_id])


# ── Gap 24: AI Prompt Registry ────────────────────────────────────────────────

class AIPrompt(Base, TimestampMixin):
    """Versioned prompt registry. One active version per key at a time."""
    __tablename__ = "ai_prompts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    key = Column(String(100), nullable=False, index=True)          # e.g. "predictions.demand_forecast"
    version = Column(Integer, nullable=False, default=1)
    title = Column(String(255), nullable=False)
    module = Column(String(50), nullable=True)                     # owning module key
    prompt_type = Column(String(50), nullable=False, default="system")   # system | user | few_shot | rag_context
    content = Column(Text, nullable=False)
    variables = Column(JSON, nullable=True)                        # list of placeholder names
    is_active = Column(Boolean, default=True, nullable=False)
    notes = Column(Text, nullable=True)
    created_by = Column(String(200), nullable=True)
