import uuid
import enum
from sqlalchemy import (
    Column, String, Text, Numeric, Integer, Boolean,
    ForeignKey, Enum, Date, DateTime, JSON,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.db.base import Base, TimestampMixin


class AIRequestStatus(str, enum.Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class AIRequestType(str, enum.Enum):
    PREDICTION = "PREDICTION"
    RECOMMENDATION = "RECOMMENDATION"
    SCENARIO = "SCENARIO"
    FORMULATION = "FORMULATION"
    DOCUMENT = "DOCUMENT"


class AIProvider(str, enum.Enum):
    ANTHROPIC = "anthropic"
    OPENAI = "openai"
    GEMINI = "gemini"
    MOCK = "mock"
    AUTO = "auto"


class AIRequest(Base, TimestampMixin):
    """Log of every AI call — for audit, cost tracking, and retry."""
    __tablename__ = "ai_requests"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    request_type = Column(Enum(AIRequestType), nullable=False)
    provider = Column(Enum(AIProvider), nullable=False, default=AIProvider.ANTHROPIC)
    model = Column(String(100), nullable=True)
    status = Column(Enum(AIRequestStatus), nullable=False, default=AIRequestStatus.PENDING)
    prompt_tokens = Column(Integer, nullable=True)
    completion_tokens = Column(Integer, nullable=True)
    latency_ms = Column(Integer, nullable=True)
    error_message = Column(Text, nullable=True)
    input_data = Column(JSON, nullable=True)        # what was sent to AI
    output_data = Column(JSON, nullable=True)       # raw AI response
    created_by_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)

    created_by = relationship("User")


class AIPrediction(Base, TimestampMixin):
    """Stored prediction result."""
    __tablename__ = "ai_predictions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    request_id = Column(UUID(as_uuid=True), ForeignKey("ai_requests.id", ondelete="SET NULL"), nullable=True)
    prediction_type = Column(String(50), nullable=False)   # sales_forecast | demand | stock_depletion | cost_trend | supplier_risk
    subject_id = Column(UUID(as_uuid=True), nullable=True)  # product_id / supplier_id / etc.
    subject_name = Column(String(255), nullable=True)
    period = Column(String(20), nullable=True)              # "2026-05" or "next_30_days"
    forecast_value = Column(Numeric(18, 4), nullable=True)
    confidence_score = Column(Numeric(5, 4), nullable=True)   # 0.0 – 1.0
    risk_level = Column(String(20), nullable=True)          # low | medium | high | critical
    trend = Column(String(20), nullable=True)               # up | down | stable
    summary = Column(Text, nullable=True)
    details = Column(JSON, nullable=True)                   # full structured output
    is_archived = Column(Boolean, default=False, nullable=False)
    created_by_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)

    request = relationship("AIRequest")
    created_by = relationship("User")


class AIRecommendation(Base, TimestampMixin):
    """Stored recommendation."""
    __tablename__ = "ai_recommendations"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    request_id = Column(UUID(as_uuid=True), ForeignKey("ai_requests.id", ondelete="SET NULL"), nullable=True)
    category = Column(String(50), nullable=False)   # pricing | stock | supplier | production | margin
    title = Column(String(255), nullable=False)
    reason = Column(Text, nullable=True)
    expected_impact = Column(Text, nullable=True)
    confidence_level = Column(String(20), nullable=True)   # low | medium | high
    priority = Column(String(20), nullable=True)           # low | medium | high | critical
    action_data = Column(JSON, nullable=True)              # structured action details
    is_actioned = Column(Boolean, default=False, nullable=False)
    is_dismissed = Column(Boolean, default=False, nullable=False)
    created_by_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)

    request = relationship("AIRequest")
    created_by = relationship("User")


class AIFormulation(Base, TimestampMixin):
    """Stored chemical formulation generated by AI."""
    __tablename__ = "ai_formulations"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    request_id = Column(UUID(as_uuid=True), ForeignKey("ai_requests.id", ondelete="SET NULL"), nullable=True)
    name = Column(String(255), nullable=False)
    product_category = Column(String(100), nullable=False)
    version = Column(String(50), nullable=False, default="standard")  # standard | low_cost | premium | eco
    target_properties = Column(JSON, nullable=True)
    cost_target = Column(Numeric(14, 4), nullable=True)
    performance_priority = Column(String(20), nullable=True)   # cost | balanced | quality
    # Full AI output
    formulation_data = Column(JSON, nullable=False)            # complete structured formulation
    estimated_cost_per_kg = Column(Numeric(14, 4), nullable=True)
    # Metadata
    is_approved = Column(Boolean, default=False, nullable=False)
    is_favorite = Column(Boolean, default=False, nullable=False)
    notes = Column(Text, nullable=True)
    created_by_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)

    request = relationship("AIRequest")
    created_by = relationship("User")


class AIScenario(Base, TimestampMixin):
    """Stored scenario simulation."""
    __tablename__ = "ai_scenarios"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    request_id = Column(UUID(as_uuid=True), ForeignKey("ai_requests.id", ondelete="SET NULL"), nullable=True)
    title = Column(String(255), nullable=False)
    scenario_type = Column(String(50), nullable=False)   # price_change | product_change | cost_change | supplier_change
    input_parameters = Column(JSON, nullable=True)
    expected_impact = Column(Text, nullable=True)
    risks = Column(JSON, nullable=True)
    opportunities = Column(JSON, nullable=True)
    simulation_data = Column(JSON, nullable=False)
    created_by_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)

    request = relationship("AIRequest")
    created_by = relationship("User")
