"""
Tests for moto_sales_service.initiate_stk_push delegation to mpesa_daraja_service.

Verifies:
- No more independent fake checkout/merchant IDs generated by moto_sales_service
- Both checkout_request_id and merchant_request_id come from the shared Daraja service
- Simulation fallback (ws_CO_SIM_*) works when credentials are absent
- Decimal amount is converted to int before passing to Daraja
"""
from __future__ import annotations

import uuid
from decimal import Decimal
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from app.services import moto_sales_service


@pytest.mark.asyncio
async def test_stk_push_no_longer_generates_independent_fake_ids():
    """initiate_stk_push must not build checkout/merchant IDs itself."""
    txn_id = uuid.uuid4()
    sim_checkout = "ws_CO_SIM_VANTEST1234567890"
    sim_merchant = "SIM_VAN12345"

    db = AsyncMock()
    db.add = MagicMock()
    db.commit = AsyncMock()
    db.refresh = AsyncMock()

    with patch(
        "app.services.moto_sales_service._daraja._stk_push_request",
        new=AsyncMock(return_value=(sim_checkout, sim_merchant, {"_simulated": True})),
    ):
        result = await moto_sales_service.initiate_stk_push(
            db=db,
            txn_id=txn_id,
            phone="254700000001",
            amount=Decimal("250"),
        )

    # Both IDs must come from Daraja, not self-generated
    assert result.checkout_request_id == sim_checkout
    assert result.merchant_request_id == sim_merchant
    assert "ws_CO_" in result.checkout_request_id
    # Must NOT be a locally constructed timestamp-based ID
    assert len(result.checkout_request_id) > 6


@pytest.mark.asyncio
async def test_stk_push_maps_both_ids_from_daraja_tuple():
    """checkout_request_id = tuple[0], merchant_request_id = tuple[1]."""
    txn_id = uuid.uuid4()
    expected_checkout = "ws_CO_LIVE_REAL_VAN_ID_001"
    expected_merchant = "MR_VAN_001"

    db = AsyncMock()
    db.add = MagicMock()
    db.commit = AsyncMock()
    db.refresh = AsyncMock()

    with patch(
        "app.services.moto_sales_service._daraja._stk_push_request",
        new=AsyncMock(return_value=(expected_checkout, expected_merchant, {})),
    ):
        result = await moto_sales_service.initiate_stk_push(
            db=db,
            txn_id=txn_id,
            phone="254711000002",
            amount=Decimal("1000"),
        )

    assert result.checkout_request_id == expected_checkout
    assert result.merchant_request_id == expected_merchant


@pytest.mark.asyncio
async def test_stk_push_converts_decimal_amount_to_int():
    """Daraja requires integer amounts — delegation must pass int(amount)."""
    txn_id = uuid.uuid4()
    mock_daraja = AsyncMock(return_value=("ws_CO_SIM_X", "SIM_X", {}))

    db = AsyncMock()
    db.add = MagicMock()
    db.commit = AsyncMock()
    db.refresh = AsyncMock()

    with patch(
        "app.services.moto_sales_service._daraja._stk_push_request",
        new=mock_daraja,
    ):
        await moto_sales_service.initiate_stk_push(
            db=db,
            txn_id=txn_id,
            phone="254700000003",
            amount=Decimal("750.50"),
        )

    call_kwargs = mock_daraja.call_args
    passed_amount = call_kwargs.kwargs.get("amount") or call_kwargs.args[1]
    assert isinstance(passed_amount, int)
    assert passed_amount == 750
