"""
Tests for mpesa_service._stk_push_request delegation to mpesa_daraja_service.

Verifies:
- No more ws_CO_PLACEHOLDER_* IDs generated by mpesa_service itself
- Simulation fallback (ws_CO_SIM_*) comes from the shared Daraja service path
- Delegation correctly extracts checkout_id from the Daraja tuple response
"""
from __future__ import annotations

from decimal import Decimal
from unittest.mock import AsyncMock, patch

import pytest

from app.services import mpesa_service


@pytest.mark.asyncio
async def test_stk_push_no_longer_returns_placeholder_id():
    """mpesa_service._stk_push_request must not generate ws_CO_PLACEHOLDER_* itself."""
    sim_checkout = "ws_CO_SIM_ABCDEF1234567890"
    sim_merchant = "SIM_12345678"
    sim_resp = {
        "CheckoutRequestID": sim_checkout,
        "MerchantRequestID": sim_merchant,
        "_simulated": True,
    }

    with patch(
        "app.services.mpesa_service._daraja._stk_push_request",
        new=AsyncMock(return_value=(sim_checkout, sim_merchant, sim_resp)),
    ):
        result = await mpesa_service._stk_push_request(
            phone="254700000001",
            amount=Decimal("500"),
            reference="SO-001",
        )

    assert result == sim_checkout
    assert "PLACEHOLDER" not in result


@pytest.mark.asyncio
async def test_stk_push_returns_checkout_id_from_daraja_response():
    """Checkout ID is extracted as the first element of the Daraja tuple."""
    expected_checkout = "ws_CO_LIVE_REALID12345678"
    live_resp = {
        "MerchantRequestID": "MR-0001",
        "CheckoutRequestID": expected_checkout,
        "ResponseCode": "0",
        "ResponseDescription": "Success",
    }

    with patch(
        "app.services.mpesa_service._daraja._stk_push_request",
        new=AsyncMock(return_value=(expected_checkout, "MR-0001", live_resp)),
    ):
        result = await mpesa_service._stk_push_request(
            phone="+254712345678",
            amount=Decimal("1500.00"),
            reference="SO-2026-099",
        )

    assert result == expected_checkout


@pytest.mark.asyncio
async def test_stk_push_converts_decimal_amount_to_int_for_daraja():
    """Daraja requires integer amounts; delegation must pass int(amount)."""
    mock_inner = AsyncMock(return_value=("ws_CO_TEST_001", "MR_TEST", {}))

    with patch(
        "app.services.mpesa_service._daraja._stk_push_request",
        new=mock_inner,
    ):
        await mpesa_service._stk_push_request(
            phone="254700000001",
            amount=Decimal("999.75"),
            reference="SO-TEST",
        )

    call_kwargs = mock_inner.call_args
    passed_amount = call_kwargs.kwargs.get("amount") or call_kwargs.args[1]
    assert isinstance(passed_amount, int)
    assert passed_amount == 999
