"""initial schema

Revision ID: 3c45d9071c98
Revises: 
Create Date: 2026-04-09 20:33:49.559337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3c45d9071c98'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_orders', sa.Column('campaign_id', sa.UUID(), nullable=True))
    op.add_column('sales_orders', sa.Column('promotion_id', sa.UUID(), nullable=True))
    op.add_column('sales_orders', sa.Column('crm_segment_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_sales_orders_campaign_id'), 'sales_orders', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_sales_orders_promotion_id'), 'sales_orders', ['promotion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_orders_promotion_id'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_campaign_id'), table_name='sales_orders')
    op.drop_column('sales_orders', 'crm_segment_id')
    op.drop_column('sales_orders', 'promotion_id')
    op.drop_column('sales_orders', 'campaign_id')
    # ### end Alembic commands ###
