"""subcontracting_system

Revision ID: 4a1b1eba5eed
Revises: 4cddbd375e74
Create Date: 2026-04-25 09:02:57.060510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4a1b1eba5eed'
down_revision: Union[str, None] = '4cddbd375e74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
