import type { HelpEntry } from "./types";

// Relative paths from docs/user-manual/ (not filesystem absolute paths)
const FR = "full-reference";
const KE = "kenya-go-live";

export const HELP_REGISTRY: HelpEntry[] = [
  // ── Core ──────────────────────────────────────────────────────────────────
  {
    id: "dashboard",
    title: "Dashboard Home",
    route: "/dashboard",
    path: "/dashboard",
    role: "manager",
    module: "core",
    description: "Overview of business KPIs, pending tasks, and quick links to all modules.",
    fullReferencePath: `${FR}/01_DASHBOARD_AND_NAVIGATION.md`,
    quickGuidePath: `${KE}/08_MANAGER_DASHBOARD_USER_MANUAL.md`,
    screenshotFile: "002_dashboard.png",
    keywords: ["dashboard", "home", "kpi", "overview", "tasks"],
  },

  // ── Admin ─────────────────────────────────────────────────────────────────
  {
    id: "admin",
    title: "Admin Workspace",
    route: "/dashboard/admin",
    path: "/dashboard/admin",
    role: "admin",
    module: "admin",
    description: "System administration: users, roles, permissions, companies, and audit logs.",
    fullReferencePath: `${FR}/10_ADMIN_AND_SECURITY.md`,
    quickGuidePath: `${KE}/01_ADMIN_USER_MANUAL.md`,
    screenshotFile: "003_admin.png",
    keywords: ["admin", "system", "configuration", "setup"],
  },
  {
    id: "admin-users",
    title: "Admin — Users",
    route: "/dashboard/admin?tab=users",
    path: "/dashboard/admin",
    tab: "users",
    role: "admin",
    module: "admin",
    description: "Create and manage ERP user accounts, passwords, and account status.",
    fullReferencePath: `${FR}/10_ADMIN_AND_SECURITY.md`,
    quickGuidePath: `${KE}/01_ADMIN_USER_MANUAL.md`,
    screenshotFile: "004_admin-users.png",
    keywords: ["users", "accounts", "password", "login"],
  },
  {
    id: "admin-roles",
    title: "Admin — Roles",
    route: "/dashboard/admin?tab=roles",
    path: "/dashboard/admin",
    tab: "roles",
    role: "admin",
    module: "admin",
    description: "Define roles that group permissions. Assign roles to users.",
    fullReferencePath: `${FR}/10_ADMIN_AND_SECURITY.md`,
    quickGuidePath: `${KE}/01_ADMIN_USER_MANUAL.md`,
    screenshotFile: "005_admin-roles.png",
    keywords: ["roles", "rbac", "access control"],
  },
  {
    id: "admin-permissions",
    title: "Admin — Permissions",
    route: "/dashboard/admin?tab=permissions",
    path: "/dashboard/admin",
    tab: "permissions",
    role: "admin",
    module: "admin",
    description: "Fine-grained permission codes that control access to ERP features.",
    fullReferencePath: `${FR}/10_ADMIN_AND_SECURITY.md`,
    quickGuidePath: `${KE}/01_ADMIN_USER_MANUAL.md`,
    screenshotFile: "006_admin-permissions.png",
    keywords: ["permissions", "access", "rbac"],
  },

  // ── Master Data ───────────────────────────────────────────────────────────
  {
    id: "products",
    title: "Products",
    route: "/dashboard/products",
    path: "/dashboard/products",
    role: "admin",
    module: "master-data",
    description: "Manage finished goods, packaging, and SKUs. Set pricing, units, and categories.",
    fullReferencePath: `${FR}/02_MASTER_DATA.md`,
    screenshotFile: "012_products.png",
    keywords: ["products", "skus", "finished goods", "pricing", "catalogue"],
  },
  {
    id: "materials",
    title: "Materials",
    route: "/dashboard/materials",
    path: "/dashboard/materials",
    role: "warehouse",
    module: "master-data",
    description: "Raw materials, packaging materials, and ingredients used in production.",
    fullReferencePath: `${FR}/02_MASTER_DATA.md`,
    screenshotFile: "013_materials.png",
    keywords: ["materials", "raw materials", "ingredients", "bom"],
  },
  {
    id: "suppliers",
    title: "Suppliers",
    route: "/dashboard/suppliers",
    path: "/dashboard/suppliers",
    role: "procurement",
    module: "master-data",
    description: "Supplier master records: contact details, payment terms, and performance ratings.",
    fullReferencePath: `${FR}/02_MASTER_DATA.md`,
    screenshotFile: "014_suppliers.png",
    keywords: ["suppliers", "vendors", "procurement", "contacts"],
  },

  // ── Procurement ───────────────────────────────────────────────────────────
  {
    id: "procurement",
    title: "Procurement",
    route: "/dashboard/procurement",
    path: "/dashboard/procurement",
    role: "procurement",
    module: "procurement",
    description: "End-to-end procurement: purchase requests, orders, deliveries, and supplier management.",
    fullReferencePath: `${FR}/03_PROCUREMENT.md`,
    quickGuidePath: `${KE}/04_PROCUREMENT_USER_MANUAL.md`,
    screenshotFile: "019_procurement.png",
    keywords: ["procurement", "purchasing", "po", "purchase order"],
  },
  {
    id: "procurement-requests",
    title: "Procurement — Purchase Requests",
    route: "/dashboard/procurement?tab=purchase-requests",
    path: "/dashboard/procurement",
    tab: "purchase-requests",
    role: "procurement",
    module: "procurement",
    description: "Raise and approve internal purchase requests before creating POs.",
    fullReferencePath: `${FR}/03_PROCUREMENT.md`,
    quickGuidePath: `${KE}/04_PROCUREMENT_USER_MANUAL.md`,
    screenshotFile: "020_procurement-requests.png",
    keywords: ["purchase request", "pr", "requisition", "approval"],
  },
  {
    id: "procurement-orders",
    title: "Procurement — Orders",
    route: "/dashboard/procurement?tab=orders",
    path: "/dashboard/procurement",
    tab: "orders",
    role: "procurement",
    module: "procurement",
    description: "Manage purchase orders sent to suppliers. Track status and expected delivery.",
    fullReferencePath: `${FR}/03_PROCUREMENT.md`,
    quickGuidePath: `${KE}/04_PROCUREMENT_USER_MANUAL.md`,
    screenshotFile: "021_procurement-orders.png",
    keywords: ["purchase order", "po", "supplier", "order"],
  },
  {
    id: "procurement-rfq",
    title: "Procurement — RFQ",
    route: "/dashboard/procurement?tab=rfq",
    path: "/dashboard/procurement",
    tab: "rfq",
    role: "procurement",
    module: "procurement",
    description: "Request for Quotation: get supplier quotes before committing to a PO.",
    fullReferencePath: `${FR}/03_PROCUREMENT.md`,
    screenshotFile: "022_procurement-rfq.png",
    keywords: ["rfq", "quotation", "quote", "supplier bid"],
  },

  // ── Inventory ─────────────────────────────────────────────────────────────
  {
    id: "inventory",
    title: "Inventory",
    route: "/dashboard/inventory",
    path: "/dashboard/inventory",
    role: "warehouse",
    module: "inventory",
    description: "Real-time stock visibility across all warehouses and locations.",
    fullReferencePath: `${FR}/04_INVENTORY_AND_WAREHOUSE.md`,
    quickGuidePath: `${KE}/03_WAREHOUSE_INVENTORY_USER_MANUAL.md`,
    screenshotFile: "027_inventory.png",
    keywords: ["inventory", "stock", "warehouse", "levels"],
  },
  {
    id: "inventory-stock",
    title: "Inventory — Stock",
    route: "/dashboard/inventory?tab=stock",
    path: "/dashboard/inventory",
    tab: "stock",
    role: "warehouse",
    module: "inventory",
    description: "View current stock levels by product, warehouse, and location.",
    fullReferencePath: `${FR}/04_INVENTORY_AND_WAREHOUSE.md`,
    quickGuidePath: `${KE}/03_WAREHOUSE_INVENTORY_USER_MANUAL.md`,
    screenshotFile: "028_inventory-stock.png",
    keywords: ["stock levels", "on hand", "available stock"],
  },
  {
    id: "inventory-movements",
    title: "Inventory — Movements",
    route: "/dashboard/inventory?tab=movements",
    path: "/dashboard/inventory",
    tab: "movements",
    role: "warehouse",
    module: "inventory",
    description: "Stock movement history: receipts, issues, transfers, and adjustments.",
    fullReferencePath: `${FR}/04_INVENTORY_AND_WAREHOUSE.md`,
    quickGuidePath: `${KE}/03_WAREHOUSE_INVENTORY_USER_MANUAL.md`,
    screenshotFile: "029_inventory-movements.png",
    keywords: ["movements", "transfers", "adjustments", "stock history"],
  },
  {
    id: "inventory-shelf-life",
    title: "Inventory — Shelf Life",
    route: "/dashboard/inventory?tab=shelf-life",
    path: "/dashboard/inventory",
    tab: "shelf-life",
    role: "warehouse",
    module: "inventory",
    description: "Monitor expiry dates and FEFO (First Expired First Out) compliance.",
    fullReferencePath: `${FR}/04_INVENTORY_AND_WAREHOUSE.md`,
    quickGuidePath: `${KE}/03_WAREHOUSE_INVENTORY_USER_MANUAL.md`,
    screenshotFile: "030_inventory-shelf-life.png",
    keywords: ["shelf life", "expiry", "fefo", "dates"],
  },
  {
    id: "inventory-cycle-count",
    title: "Inventory — Cycle Count",
    route: "/dashboard/inventory?tab=cycle-count",
    path: "/dashboard/inventory",
    tab: "cycle-count",
    role: "warehouse",
    module: "inventory",
    description: "Run scheduled cycle counts and physical inventory audits.",
    fullReferencePath: `${FR}/04_INVENTORY_AND_WAREHOUSE.md`,
    quickGuidePath: `${KE}/03_WAREHOUSE_INVENTORY_USER_MANUAL.md`,
    screenshotFile: "031_inventory-cycle-count.png",
    keywords: ["cycle count", "stock count", "audit", "physical inventory"],
  },
  {
    id: "wms",
    title: "WMS — Warehouse Management",
    route: "/dashboard/wms",
    path: "/dashboard/wms",
    role: "warehouse",
    module: "wms",
    description: "Warehouse operations: picking, putaway, zones, locations, and quarantine.",
    fullReferencePath: `${FR}/04_INVENTORY_AND_WAREHOUSE.md`,
    quickGuidePath: `${KE}/03_WAREHOUSE_INVENTORY_USER_MANUAL.md`,
    screenshotFile: "035_wms.png",
    keywords: ["wms", "warehouse", "picking", "putaway", "location"],
  },
  {
    id: "wms-zones",
    title: "WMS — Zones",
    route: "/dashboard/wms?tab=zones",
    path: "/dashboard/wms",
    tab: "zones",
    role: "warehouse",
    module: "wms",
    description: "Configure warehouse zones: storage areas, ambient, cold, hazardous.",
    fullReferencePath: `${FR}/04_INVENTORY_AND_WAREHOUSE.md`,
    quickGuidePath: `${KE}/03_WAREHOUSE_INVENTORY_USER_MANUAL.md`,
    screenshotFile: "036_wms-zones.png",
    keywords: ["zones", "warehouse layout", "storage areas"],
  },
  {
    id: "wms-locations",
    title: "WMS — Locations",
    route: "/dashboard/wms?tab=locations",
    path: "/dashboard/wms",
    tab: "locations",
    role: "warehouse",
    module: "wms",
    description: "Bin and shelf locations within warehouse zones.",
    fullReferencePath: `${FR}/04_INVENTORY_AND_WAREHOUSE.md`,
    screenshotFile: "037_wms-locations.png",
    keywords: ["locations", "bins", "shelves", "slotting"],
  },

  // ── Production ────────────────────────────────────────────────────────────
  {
    id: "production",
    title: "Production",
    route: "/dashboard/production",
    path: "/dashboard/production",
    role: "production",
    module: "production",
    description: "Production order management, execution tracking, and manufacturing operations.",
    fullReferencePath: `${FR}/05_PRODUCTION.md`,
    quickGuidePath: `${KE}/02_PRODUCTION_USER_MANUAL.md`,
    screenshotFile: "039_production.png",
    keywords: ["production", "manufacturing", "orders", "batches"],
  },
  {
    id: "production-orders",
    title: "Production — Orders",
    route: "/dashboard/production?tab=orders",
    path: "/dashboard/production",
    tab: "orders",
    role: "production",
    module: "production",
    description: "Create and manage production orders. Track progress and output quantities.",
    fullReferencePath: `${FR}/05_PRODUCTION.md`,
    quickGuidePath: `${KE}/02_PRODUCTION_USER_MANUAL.md`,
    screenshotFile: "040_production-orders.png",
    keywords: ["production orders", "mo", "manufacturing order", "batch"],
  },
  {
    id: "production-execution",
    title: "Production — Execution",
    route: "/dashboard/production?tab=execution",
    path: "/dashboard/production",
    tab: "execution",
    role: "production",
    module: "production",
    description: "Real-time production floor execution: start, pause, and complete operations.",
    fullReferencePath: `${FR}/05_PRODUCTION.md`,
    quickGuidePath: `${KE}/02_PRODUCTION_USER_MANUAL.md`,
    screenshotFile: "041_production-execution.png",
    keywords: ["execution", "floor", "operations", "real-time"],
  },
  {
    id: "production-material-flow",
    title: "Production — Material Flow",
    route: "/dashboard/production?tab=material-flow",
    path: "/dashboard/production",
    tab: "material-flow",
    role: "production",
    module: "production",
    description: "Material consumption and component issuance for production orders.",
    fullReferencePath: `${FR}/05_PRODUCTION.md`,
    quickGuidePath: `${KE}/02_PRODUCTION_USER_MANUAL.md`,
    screenshotFile: "042_production-material-flow.png",
    keywords: ["material flow", "components", "consumption", "issuance"],
  },
  {
    id: "production-costing",
    title: "Production — Costing",
    route: "/dashboard/production?tab=costing",
    path: "/dashboard/production",
    tab: "costing",
    role: "manager",
    module: "production",
    description: "Production cost analysis: material, labour, and overhead per batch.",
    fullReferencePath: `${FR}/05_PRODUCTION.md`,
    quickGuidePath: `${KE}/02_PRODUCTION_USER_MANUAL.md`,
    screenshotFile: "043_production-costing.png",
    keywords: ["costing", "cost", "cogs", "overhead", "labour"],
  },
  {
    id: "production-oee",
    title: "Production — OEE",
    route: "/dashboard/production?tab=oee",
    path: "/dashboard/production",
    tab: "oee",
    role: "manager",
    module: "production",
    description: "Overall Equipment Effectiveness metrics: availability, performance, quality.",
    fullReferencePath: `${FR}/05_PRODUCTION.md`,
    screenshotFile: "046_production-oee.png",
    keywords: ["oee", "equipment effectiveness", "availability", "performance"],
  },
  {
    id: "shop-floor",
    title: "Shop Floor",
    route: "/dashboard/shop-floor",
    path: "/dashboard/shop-floor",
    role: "production",
    module: "production",
    description: "Operator terminals and supervisor view for real-time shop floor control.",
    fullReferencePath: `${FR}/05_PRODUCTION.md`,
    quickGuidePath: `${KE}/02_PRODUCTION_USER_MANUAL.md`,
    screenshotFile: "052_shop-floor.png",
    keywords: ["shop floor", "operator", "terminal", "supervisor"],
  },
  {
    id: "bom",
    title: "BOM & Formulas",
    route: "/dashboard/bom",
    path: "/dashboard/bom",
    role: "production",
    module: "bom",
    description: "Bill of Materials and formulas: define component structures for production.",
    fullReferencePath: `${FR}/05_PRODUCTION.md`,
    quickGuidePath: `${KE}/02_PRODUCTION_USER_MANUAL.md`,
    screenshotFile: "055_bom.png",
    keywords: ["bom", "bill of materials", "formula", "recipe structure"],
  },
  {
    id: "planning",
    title: "Production Planning",
    route: "/dashboard/planning",
    path: "/dashboard/planning",
    role: "production",
    module: "planning",
    description: "MRP/MPS planning: generate production and procurement requirements.",
    fullReferencePath: `${FR}/05_PRODUCTION.md`,
    screenshotFile: "059_planning.png",
    keywords: ["planning", "mrp", "mps", "demand", "capacity"],
  },

  // ── Quality ───────────────────────────────────────────────────────────────
  {
    id: "quality",
    title: "Quality",
    route: "/dashboard/quality",
    path: "/dashboard/quality",
    role: "quality",
    module: "quality",
    description: "Quality inspections, QMS, allergen management, and certificates of analysis.",
    fullReferencePath: `${FR}/06_QUALITY_AND_COMPLIANCE.md`,
    quickGuidePath: `${KE}/05_QUALITY_CONTROL_USER_MANUAL.md`,
    screenshotFile: "063_quality.png",
    keywords: ["quality", "qc", "inspection", "qa"],
  },
  {
    id: "quality-inspections",
    title: "Quality — Inspections",
    route: "/dashboard/quality?tab=inspections",
    path: "/dashboard/quality",
    tab: "inspections",
    role: "quality",
    module: "quality",
    description: "Record and review quality inspections for incoming goods and production.",
    fullReferencePath: `${FR}/06_QUALITY_AND_COMPLIANCE.md`,
    quickGuidePath: `${KE}/05_QUALITY_CONTROL_USER_MANUAL.md`,
    screenshotFile: "064_quality-inspections.png",
    keywords: ["inspections", "incoming", "sampling", "pass/fail"],
  },
  {
    id: "quality-qms",
    title: "Quality — QMS",
    route: "/dashboard/quality?tab=qms",
    path: "/dashboard/quality",
    tab: "qms",
    role: "quality",
    module: "quality",
    description: "Quality Management System: procedures, non-conformances, and corrective actions.",
    fullReferencePath: `${FR}/06_QUALITY_AND_COMPLIANCE.md`,
    quickGuidePath: `${KE}/05_QUALITY_CONTROL_USER_MANUAL.md`,
    screenshotFile: "065_quality-qms.png",
    keywords: ["qms", "non-conformance", "ncr", "capa", "corrective action"],
  },
  {
    id: "quality-allergen",
    title: "Quality — Allergen",
    route: "/dashboard/quality?tab=allergen",
    path: "/dashboard/quality",
    tab: "allergen",
    role: "quality",
    module: "quality",
    description: "Allergen tracking and cross-contamination risk management.",
    fullReferencePath: `${FR}/06_QUALITY_AND_COMPLIANCE.md`,
    quickGuidePath: `${KE}/05_QUALITY_CONTROL_USER_MANUAL.md`,
    screenshotFile: "066_quality-allergen.png",
    keywords: ["allergen", "cross contamination", "gluten", "nuts", "dairy"],
  },
  {
    id: "compliance",
    title: "Compliance",
    route: "/dashboard/compliance",
    path: "/dashboard/compliance",
    role: "quality",
    module: "compliance",
    description: "Regulatory compliance: GS1 barcodes, certificates, and regulatory submissions.",
    fullReferencePath: `${FR}/06_QUALITY_AND_COMPLIANCE.md`,
    quickGuidePath: `${KE}/05_QUALITY_CONTROL_USER_MANUAL.md`,
    screenshotFile: "069_compliance.png",
    keywords: ["compliance", "regulatory", "kebs", "gs1", "barcode"],
  },

  // ── Sales ─────────────────────────────────────────────────────────────────
  {
    id: "sales",
    title: "Sales",
    route: "/dashboard/sales",
    path: "/dashboard/sales",
    role: "sales",
    module: "sales",
    description: "Complete sales management: orders, invoices, customers, and distributions.",
    fullReferencePath: `${FR}/07_SALES_AND_DISTRIBUTION.md`,
    quickGuidePath: `${KE}/06_SALES_LOGISTICS_USER_MANUAL.md`,
    screenshotFile: "072_sales.png",
    keywords: ["sales", "orders", "customers", "invoices", "revenue"],
  },
  {
    id: "sales-orders",
    title: "Sales — Orders",
    route: "/dashboard/sales?tab=orders",
    path: "/dashboard/sales",
    tab: "orders",
    role: "sales",
    module: "sales",
    description: "Create and manage customer sales orders. Track fulfilment status.",
    fullReferencePath: `${FR}/07_SALES_AND_DISTRIBUTION.md`,
    quickGuidePath: `${KE}/06_SALES_LOGISTICS_USER_MANUAL.md`,
    screenshotFile: "073_sales-orders.png",
    keywords: ["sales order", "so", "customer order", "fulfilment"],
  },
  {
    id: "sales-invoices",
    title: "Sales — Invoices",
    route: "/dashboard/sales?tab=invoices",
    path: "/dashboard/sales",
    tab: "invoices",
    role: "sales",
    module: "sales",
    description: "Generate and manage sales invoices. Track payment status.",
    fullReferencePath: `${FR}/07_SALES_AND_DISTRIBUTION.md`,
    quickGuidePath: `${KE}/06_SALES_LOGISTICS_USER_MANUAL.md`,
    screenshotFile: "074_sales-invoices.png",
    keywords: ["invoices", "billing", "payment", "ar"],
  },
  {
    id: "sales-van-sales",
    title: "Sales — Van Sales",
    route: "/dashboard/sales?tab=van-sales",
    path: "/dashboard/sales",
    tab: "van-sales",
    role: "sales",
    module: "sales",
    description: "Mobile van sales operations: load, sell, and reconcile field sales.",
    fullReferencePath: `${FR}/07_SALES_AND_DISTRIBUTION.md`,
    quickGuidePath: `${KE}/06_SALES_LOGISTICS_USER_MANUAL.md`,
    screenshotFile: "077_sales-van-sales.png",
    keywords: ["van sales", "field sales", "route sales", "mobile"],
  },
  {
    id: "sales-collections",
    title: "Sales — Collections",
    route: "/dashboard/sales?tab=collections",
    path: "/dashboard/sales",
    tab: "collections",
    role: "sales",
    module: "sales",
    description: "Customer payment collections including M-Pesa and cash reconciliation.",
    fullReferencePath: `${FR}/07_SALES_AND_DISTRIBUTION.md`,
    quickGuidePath: `${KE}/06_SALES_LOGISTICS_USER_MANUAL.md`,
    screenshotFile: "079_sales-collections.png",
    keywords: ["collections", "mpesa", "cash", "payment", "reconciliation"],
  },
  {
    id: "logistics",
    title: "Logistics",
    route: "/dashboard/logistics",
    path: "/dashboard/logistics",
    role: "sales",
    module: "logistics",
    description: "Delivery management: shipments, fleet tracking, and route planning.",
    fullReferencePath: `${FR}/07_SALES_AND_DISTRIBUTION.md`,
    quickGuidePath: `${KE}/06_SALES_LOGISTICS_USER_MANUAL.md`,
    screenshotFile: "083_logistics.png",
    keywords: ["logistics", "delivery", "fleet", "shipment", "distribution"],
  },

  // ── Finance ───────────────────────────────────────────────────────────────
  {
    id: "finance",
    title: "Finance",
    route: "/dashboard/finance",
    path: "/dashboard/finance",
    role: "finance",
    module: "finance",
    description: "Complete financial management: accounting, receivables, payables, and reporting.",
    fullReferencePath: `${FR}/08_FINANCE.md`,
    screenshotFile: "087_finance.png",
    keywords: ["finance", "accounting", "ledger", "financial"],
  },
  {
    id: "finance-accounting",
    title: "Finance — Accounting",
    route: "/dashboard/finance?tab=accounting",
    path: "/dashboard/finance",
    tab: "accounting",
    role: "finance",
    module: "finance",
    description: "General ledger, journal entries, and chart of accounts.",
    fullReferencePath: `${FR}/08_FINANCE.md`,
    screenshotFile: "088_finance-accounting.png",
    keywords: ["accounting", "journal", "ledger", "gl", "chart of accounts"],
  },
  {
    id: "finance-bank-recon",
    title: "Finance — Bank Reconciliation",
    route: "/dashboard/finance?tab=bank-recon",
    path: "/dashboard/finance",
    tab: "bank-recon",
    role: "finance",
    module: "finance",
    description: "Match bank statements to system transactions and resolve differences.",
    fullReferencePath: `${FR}/08_FINANCE.md`,
    screenshotFile: "089_finance-bank-recon.png",
    keywords: ["bank recon", "reconciliation", "bank statement", "matching"],
  },
  {
    id: "finance-mpesa",
    title: "Finance — M-Pesa",
    route: "/dashboard/finance?tab=mpesa",
    path: "/dashboard/finance",
    tab: "mpesa",
    role: "finance",
    module: "finance",
    description: "M-Pesa payment integration: receive, reconcile, and report M-Pesa transactions.",
    fullReferencePath: `${FR}/08_FINANCE.md`,
    screenshotFile: "094_finance-mpesa.png",
    keywords: ["mpesa", "mobile money", "kenya", "payments"],
  },
  {
    id: "finance-tax",
    title: "Finance — Tax (eTIMS)",
    route: "/dashboard/finance?tab=tax",
    path: "/dashboard/finance",
    tab: "tax",
    role: "finance",
    module: "finance",
    description: "Kenya eTIMS tax compliance: VAT, withholding tax, and KRA submission.",
    fullReferencePath: `${FR}/08_FINANCE.md`,
    screenshotFile: "095_finance-tax.png",
    keywords: ["tax", "etims", "vat", "kra", "kenya revenue", "withholding"],
  },
  {
    id: "finance-fixed-assets",
    title: "Finance — Fixed Assets",
    route: "/dashboard/finance?tab=fixed-assets",
    path: "/dashboard/finance",
    tab: "fixed-assets",
    role: "finance",
    module: "finance",
    description: "Track company fixed assets, depreciation schedules, and disposals.",
    fullReferencePath: `${FR}/08_FINANCE.md`,
    screenshotFile: "090_finance-fixed-assets.png",
    keywords: ["fixed assets", "depreciation", "capex", "assets"],
  },

  // ── HR & Payroll ──────────────────────────────────────────────────────────
  {
    id: "hr",
    title: "HR",
    route: "/dashboard/hr",
    path: "/dashboard/hr",
    role: "hr",
    module: "hr",
    description: "Human resources management: employees, attendance, leave, and appraisals.",
    fullReferencePath: `${FR}/09_HR_AND_PAYROLL.md`,
    quickGuidePath: `${KE}/07_HR_USER_MANUAL.md`,
    screenshotFile: "096_hr.png",
    keywords: ["hr", "human resources", "employees", "staff"],
  },
  {
    id: "hr-employees",
    title: "HR — Employees",
    route: "/dashboard/hr?tab=employees",
    path: "/dashboard/hr",
    tab: "employees",
    role: "hr",
    module: "hr",
    description: "Employee profiles: personal details, employment history, and documents.",
    fullReferencePath: `${FR}/09_HR_AND_PAYROLL.md`,
    quickGuidePath: `${KE}/07_HR_USER_MANUAL.md`,
    screenshotFile: "097_hr-employees.png",
    keywords: ["employees", "staff", "profiles", "employment"],
  },
  {
    id: "hr-attendance",
    title: "HR — Attendance",
    route: "/dashboard/hr?tab=attendance",
    path: "/dashboard/hr",
    tab: "attendance",
    role: "hr",
    module: "hr",
    description: "Time and attendance tracking: clock-in/out, shifts, and overtime.",
    fullReferencePath: `${FR}/09_HR_AND_PAYROLL.md`,
    quickGuidePath: `${KE}/07_HR_USER_MANUAL.md`,
    screenshotFile: "098_hr-attendance.png",
    keywords: ["attendance", "time", "clock in", "shifts", "overtime"],
  },
  {
    id: "hr-payroll",
    title: "HR — Payroll",
    route: "/dashboard/hr?tab=payroll",
    path: "/dashboard/hr",
    tab: "payroll",
    role: "hr",
    module: "hr",
    description: "Link to payroll processing. View payroll runs linked to HR records.",
    fullReferencePath: `${FR}/09_HR_AND_PAYROLL.md`,
    quickGuidePath: `${KE}/07_HR_USER_MANUAL.md`,
    screenshotFile: "099_hr-payroll.png",
    keywords: ["payroll", "salary", "payslip"],
  },
  {
    id: "hr-leave",
    title: "HR — Leave",
    route: "/dashboard/hr?tab=leave",
    path: "/dashboard/hr",
    tab: "leave",
    role: "hr",
    module: "hr",
    description: "Leave management: applications, approvals, balances, and leave types.",
    fullReferencePath: `${FR}/09_HR_AND_PAYROLL.md`,
    quickGuidePath: `${KE}/07_HR_USER_MANUAL.md`,
    screenshotFile: "100_hr-leave.png",
    keywords: ["leave", "annual leave", "sick leave", "absence"],
  },
  {
    id: "hr-recruitment",
    title: "HR — Recruitment",
    route: "/dashboard/hr?tab=recruitment",
    path: "/dashboard/hr",
    tab: "recruitment",
    role: "hr",
    module: "hr",
    description: "Recruitment pipeline: job openings, applications, and hiring decisions.",
    fullReferencePath: `${FR}/09_HR_AND_PAYROLL.md`,
    quickGuidePath: `${KE}/07_HR_USER_MANUAL.md`,
    screenshotFile: "101_hr-recruitment.png",
    keywords: ["recruitment", "hiring", "jobs", "applicants", "pipeline"],
  },
  {
    id: "payroll",
    title: "Payroll",
    route: "/dashboard/payroll",
    path: "/dashboard/payroll",
    role: "hr",
    module: "payroll",
    description: "Payroll processing for Kenya: PAYE, NHIF, NSSF, and payslip generation.",
    fullReferencePath: `${FR}/09_HR_AND_PAYROLL.md`,
    quickGuidePath: `${KE}/07_HR_USER_MANUAL.md`,
    screenshotFile: "106_payroll.png",
    keywords: ["payroll", "paye", "nhif", "nssf", "kenya payroll", "salary"],
  },
  {
    id: "payroll-profiles",
    title: "Payroll — Profiles",
    route: "/dashboard/payroll?tab=profiles",
    path: "/dashboard/payroll",
    tab: "profiles",
    role: "hr",
    module: "payroll",
    description: "Employee payroll profiles: salary grade, allowances, and deductions setup.",
    fullReferencePath: `${FR}/09_HR_AND_PAYROLL.md`,
    quickGuidePath: `${KE}/07_HR_USER_MANUAL.md`,
    screenshotFile: "107_payroll-profiles.png",
    keywords: ["payroll profile", "salary", "allowances", "deductions"],
  },
  {
    id: "payroll-reports",
    title: "Payroll — Reports",
    route: "/dashboard/payroll?tab=reports",
    path: "/dashboard/payroll",
    tab: "reports",
    role: "hr",
    module: "payroll",
    description: "Payroll reports: payslip batch export, P9 forms, and statutory returns.",
    fullReferencePath: `${FR}/09_HR_AND_PAYROLL.md`,
    quickGuidePath: `${KE}/07_HR_USER_MANUAL.md`,
    screenshotFile: "108_payroll-reports.png",
    keywords: ["payroll reports", "p9", "statutory", "payslip export"],
  },

  // ── Analytics ─────────────────────────────────────────────────────────────
  {
    id: "analytics",
    title: "Analytics",
    route: "/dashboard/analytics",
    path: "/dashboard/analytics",
    role: "manager",
    module: "analytics",
    description: "Business intelligence dashboards: sales, production, finance, and operations.",
    fullReferencePath: `${FR}/12_REPORTS_AND_EXPORTS.md`,
    quickGuidePath: `${KE}/08_MANAGER_DASHBOARD_USER_MANUAL.md`,
    screenshotFile: "109_analytics.png",
    keywords: ["analytics", "reports", "bi", "dashboard", "kpi"],
  },

  // ── AI ────────────────────────────────────────────────────────────────────
  {
    id: "ai",
    title: "AI Assistant",
    route: "/dashboard/ai",
    path: "/dashboard/ai",
    role: "manager",
    module: "ai",
    description: "AI-powered analysis, forecasting, and operational recommendations.",
    fullReferencePath: `${FR}/11_AI_AND_AUTOMATION.md`,
    screenshotFile: "121_ai.png",
    keywords: ["ai", "artificial intelligence", "forecast", "automation"],
  },
];

export const HELP_REGISTRY_MAP = new Map<string, HelpEntry>(
  HELP_REGISTRY.map((e) => [e.route, e])
);

export const HELP_MODULES = Array.from(new Set(HELP_REGISTRY.map((e) => e.module))).sort();
export const HELP_ROLES = Array.from(new Set(HELP_REGISTRY.map((e) => e.role))).sort();
