import { NextRequest, NextResponse } from "next/server";

/**
 * Redirect map: old dashboard route → new workspace + query params.
 * Kept inline here (not imported) so this file works cleanly at Edge Runtime.
 * Source of truth is routeRedirectMap.ts — keep in sync when updating.
 */
const REDIRECTS: Record<string, { p: string; t?: string; d?: string }> = {
  // Inventory
  "/dashboard/movements":                       { p: "/dashboard/inventory", t: "movements" },
  "/dashboard/cycle-count":                     { p: "/dashboard/inventory", t: "cycle-count" },
  "/dashboard/shelf-life":                      { p: "/dashboard/inventory", t: "shelf-life" },
  "/dashboard/traceability":                    { p: "/dashboard/inventory", t: "traceability" },
  // Warehouses
  "/dashboard/wms":                             { p: "/dashboard/warehouses", t: "wms" },
  "/dashboard/putaway":                         { p: "/dashboard/warehouses", t: "wms" },
  "/dashboard/containers":                      { p: "/dashboard/logistics", t: "containers" },
  // Procurement
  "/dashboard/procurement-suggestion":          { p: "/dashboard/procurement", t: "suggestions" },
  "/dashboard/subcontracting":                  { p: "/dashboard/procurement", t: "subcontracting" },
  "/dashboard/copacking":                       { p: "/dashboard/procurement", t: "subcontracting" },
  "/dashboard/landed-cost":                     { p: "/dashboard/procurement", t: "landed-cost" },
  "/dashboard/supplier-portal":                 { p: "/dashboard/procurement", t: "supplier-portal" },
  // Sales
  "/dashboard/price-lists":                     { p: "/dashboard/sales", t: "price-lists" },
  "/dashboard/dynamic-pricing":                 { p: "/dashboard/sales", t: "dynamic-pricing" },
  "/dashboard/contracts":                       { p: "/dashboard/sales", t: "contracts" },
  "/dashboard/recurring-orders":                { p: "/dashboard/sales", t: "recurring" },
  "/dashboard/commissions":                     { p: "/dashboard/sales", t: "commissions" },
  "/dashboard/secondary-sales":                 { p: "/dashboard/sales", t: "secondary" },
  "/dashboard/van-sales":                       { p: "/dashboard/sales", t: "van-sales" },
  "/dashboard/portal":                          { p: "/dashboard/sales", t: "portal" },
  // Sales child routes (static; dynamic [id] handled by file-level redirect to preserve ID)
  "/dashboard/sales/pod":                       { p: "/dashboard/sales", t: "delivery" },
  "/dashboard/sales/customer-statement":        { p: "/dashboard/sales", t: "customers" },
  // CRM child routes (static + prefix for records/[id])
  "/dashboard/crm/ai":                          { p: "/dashboard/crm", t: "overview" },
  "/dashboard/crm/overdue":                     { p: "/dashboard/crm", t: "pipeline" },
  "/dashboard/crm/qualify":                     { p: "/dashboard/crm", t: "leads" },
  "/dashboard/crm/records":                     { p: "/dashboard/crm", t: "overview" },
  // CRM alias modules
  "/dashboard/loyalty":                         { p: "/dashboard/crm", t: "loyalty" },
  "/dashboard/nps":                             { p: "/dashboard/crm", t: "nps" },
  "/dashboard/surveys":                         { p: "/dashboard/crm", t: "surveys" },
  // Marketing
  "/dashboard/tpm":                             { p: "/dashboard/marketing", t: "tpm" },
  "/dashboard/promotions":                      { p: "/dashboard/marketing", t: "promotions-schemes" },
  "/dashboard/market-intelligence":             { p: "/dashboard/marketing", t: "market-intel" },
  // Marketing workspace child routes (prefix match covers /[id], /new, etc.)
  "/dashboard/marketing/campaigns":             { p: "/dashboard/marketing", t: "campaigns" },
  "/dashboard/marketing/ads":                   { p: "/dashboard/marketing", t: "ads" },
  "/dashboard/marketing/brand-spend":           { p: "/dashboard/marketing", t: "brand-spend" },
  "/dashboard/marketing/ecommerce":             { p: "/dashboard/marketing", t: "ecommerce" },
  "/dashboard/marketing/influencers":           { p: "/dashboard/marketing", t: "influencers" },
  "/dashboard/marketing/promotions":            { p: "/dashboard/marketing", t: "promotions" },
  "/dashboard/marketing/segments":              { p: "/dashboard/marketing", t: "segments" },
  "/dashboard/marketing/social-media":          { p: "/dashboard/marketing", t: "social-media" },
  "/dashboard/marketing/trade-spend":           { p: "/dashboard/marketing", t: "trade-spend" },
  "/dashboard/marketing/visits":                { p: "/dashboard/marketing", t: "visits" },
  "/dashboard/marketing/ai-optimizer":          { p: "/dashboard/marketing", t: "analytics" },
  // Finance
  "/dashboard/finance/accounting":              { p: "/dashboard/finance", t: "accounting" },
  "/dashboard/bank-reconciliation":             { p: "/dashboard/finance", t: "bank-recon" },
  "/dashboard/invoice-match":                   { p: "/dashboard/finance", t: "invoice-match" },
  "/dashboard/fixed-assets":                    { p: "/dashboard/finance", t: "fixed-assets" },
  "/dashboard/dimensions":                      { p: "/dashboard/finance", t: "dimensions" },
  "/dashboard/dunning":                         { p: "/dashboard/finance", t: "dunning" },
  "/dashboard/tax":                             { p: "/dashboard/finance", t: "tax" },
  "/dashboard/bank-api":                        { p: "/dashboard/finance", t: "bank-api" },
  "/dashboard/expenses":                        { p: "/dashboard/hr", t: "expenses" },
  // Production workspace child routes
  "/dashboard/production/advanced":             { p: "/dashboard/production", t: "scheduling" },
  "/dashboard/production/ai":                   { p: "/dashboard/production", t: "plans" },
  "/dashboard/production/orders":               { p: "/dashboard/production", t: "orders" },
  "/dashboard/production/plans":                { p: "/dashboard/production", t: "plans" },
  "/dashboard/production/shifts":               { p: "/dashboard/production", t: "scheduling" },
  "/dashboard/production/work-orders":          { p: "/dashboard/production", t: "orders" },
  // Production sub-modules
  "/dashboard/production-execution":            { p: "/dashboard/production", t: "execution" },
  "/dashboard/machine-ops":                     { p: "/dashboard/production", t: "machine-ops" },
  "/dashboard/material-flow":                   { p: "/dashboard/production", t: "material-flow" },
  "/dashboard/projects":                        { p: "/dashboard/production", t: "projects" },
  // Planning (no /dashboard/planning entry — it IS the workspace, would cause a loop)
  // Child pages of the planning workspace redirect to specific tabs:
  "/dashboard/planning/schedule":               { p: "/dashboard/planning", t: "advanced" },
  "/dashboard/planning/capacity":               { p: "/dashboard/planning", t: "advanced" },
  "/dashboard/planning/bottlenecks":            { p: "/dashboard/planning", t: "advanced" },
  "/dashboard/planning/simulation":             { p: "/dashboard/planning", t: "advanced" },
  "/dashboard/planning/changeover":             { p: "/dashboard/planning", t: "advanced" },
  "/dashboard/mrp":                             { p: "/dashboard/planning", t: "mrp" },
  "/dashboard/mps":                             { p: "/dashboard/planning", t: "mps" },
  "/dashboard/kanban":                          { p: "/dashboard/planning", t: "kanban" },
  // Quality
  "/dashboard/qms":                             { p: "/dashboard/quality", t: "qms" },
  "/dashboard/allergen":                        { p: "/dashboard/quality", t: "allergen" },
  "/dashboard/brand-assets":                    { p: "/dashboard/quality", t: "brand-assets" },
  "/dashboard/quality/consumer-complaints":     { p: "/dashboard/quality", t: "consumer-complaints" },
  // Compliance
  "/dashboard/gs1":                             { p: "/dashboard/compliance", t: "gs1" },
  // Utilities
  "/dashboard/iot":                             { p: "/dashboard/utility-management", t: "iot" },
  "/dashboard/esg":                             { p: "/dashboard/utility-management", t: "esg" },
  // Utility-management workspace child routes
  "/dashboard/utility-management/categories":   { p: "/dashboard/utility-management", t: "assets" },
  "/dashboard/utility-management/kpi-center":   { p: "/dashboard/utility-management", t: "kpi-center" },
  "/dashboard/utility-management/reports":      { p: "/dashboard/utility-management", t: "reports" },
  // Logistics
  "/dashboard/fleet":                           { p: "/dashboard/logistics", t: "fleet" },
  "/dashboard/logistics/containers":            { p: "/dashboard/logistics", t: "containers" },
  // HR
  "/dashboard/recruitment":                     { p: "/dashboard/hr", t: "recruitment" },
  "/dashboard/ess":                             { p: "/dashboard/hr", t: "ess" },
  "/dashboard/appraisals":                      { p: "/dashboard/hr", t: "appraisals" },
  "/dashboard/training":                        { p: "/dashboard/hr", t: "training" },
  "/dashboard/timesheets":                      { p: "/dashboard/hr", t: "timesheets" },
  // Documents child routes
  "/dashboard/documents/new":                   { p: "/dashboard/documents", d: "create" },
  // Documents alias modules
  "/dashboard/knowledge-base":                  { p: "/dashboard/documents", t: "knowledge-base" },
  "/dashboard/esign":                           { p: "/dashboard/documents", t: "esign" },
  // Communication
  "/dashboard/chatter":                         { p: "/dashboard/communication", t: "chatter" },
  "/dashboard/calendar":                        { p: "/dashboard/communication", t: "calendar" },
  "/dashboard/messages":                        { p: "/dashboard/communication", t: "messages" },
  "/dashboard/email":                           { p: "/dashboard/communication", t: "email" },
  "/dashboard/whatsapp":                        { p: "/dashboard/communication", t: "whatsapp" },
  "/dashboard/calls":                           { p: "/dashboard/communication", t: "calls" },
  "/dashboard/meetings":                        { p: "/dashboard/communication", t: "meetings" },
  "/dashboard/notification-center":             { p: "/dashboard/communication", t: "notifications" },
  // Analytics
  "/dashboard/report-builder":                  { p: "/dashboard/analytics", t: "report-builder" },
  "/dashboard/reports":                         { p: "/dashboard/analytics", t: "reports" },
  // Admin
  "/dashboard/users":                           { p: "/dashboard/admin", t: "users" },
  "/dashboard/roles":                           { p: "/dashboard/admin", t: "roles" },
  "/dashboard/permissions":                     { p: "/dashboard/admin", t: "permissions" },
  "/dashboard/companies":                       { p: "/dashboard/admin", t: "companies" },
  "/dashboard/security":                        { p: "/dashboard/admin", t: "security" },
  "/dashboard/approvals":                       { p: "/dashboard/admin", t: "approvals" },
  "/dashboard/custom-fields":                   { p: "/dashboard/admin", t: "custom-fields" },
  "/dashboard/utilities":                       { p: "/dashboard/admin", t: "system-config" },
  "/dashboard/mobile":                          { p: "/dashboard/admin", t: "mobile" },
  "/dashboard/logs":                            { p: "/dashboard/admin", t: "logs" },
  "/dashboard/import-history":                  { p: "/dashboard/admin", t: "import-history" },
  // Integrations
  "/dashboard/webhooks":                        { p: "/dashboard/integrations", t: "webhooks" },
  "/dashboard/developer":                       { p: "/dashboard/integrations", t: "developer" },
  // Payroll (top-level alias → HR payroll tab)
  "/dashboard/payroll":                         { p: "/dashboard/hr", t: "payroll" },
};

/** Real standalone pages — skip prefix-redirect so the page renders instead of redirecting */
const BYPASS_PREFIX_REDIRECT = new Set([
  // MPS real standalone pages (restored Round 13)
  "/dashboard/mps/planning-board",
  "/dashboard/mps/capacity",
  "/dashboard/mps/campaigns",
  "/dashboard/mps/whatif",
  // Cycle Count real standalone pages (restored Wave 1A)
  "/dashboard/cycle-count/plans",
  "/dashboard/cycle-count/tasks",
  "/dashboard/cycle-count/entries",
  "/dashboard/cycle-count/variances",
  "/dashboard/cycle-count/reports",
  // Critical create/new pages (restored Wave 1A)
  "/dashboard/custom-fields/new-field",
  "/dashboard/calendar/new-event",
  "/dashboard/surveys/new",
  "/dashboard/documents/new",
  "/dashboard/knowledge-base/articles/new",
  "/dashboard/fixed-assets/assets/new",
  "/dashboard/expenses/claims/new",
  "/dashboard/recruitment/requisitions/new",
  "/dashboard/appraisals/records/new",
  "/dashboard/marketing/campaigns/new",
  "/dashboard/marketing/promotions/new",
  "/dashboard/marketing/trade-spend/new",
  "/dashboard/marketing/ads/new",
  "/dashboard/marketing/social-media/new",
  "/dashboard/marketing/segments/new",
  "/dashboard/marketing/influencers/new",
  "/dashboard/marketing/visits/new",
  "/dashboard/marketing/brand-spend/new",
  "/dashboard/tpm/plans/new",
  "/dashboard/tpm/promotions/new",
  "/dashboard/mrp/run",
  "/dashboard/landed-cost/new",
  "/dashboard/machine-ops/runtime",
  "/dashboard/contracts/new",
  "/dashboard/recurring-orders/templates/new",
  "/dashboard/van-sales/vans/new",
  // Operational pages (restored Wave 1B)
  "/dashboard/custom-fields/fields",
  "/dashboard/custom-fields/form-builder",
  "/dashboard/custom-fields/workflow-rules",
  "/dashboard/custom-fields/values",
  "/dashboard/mobile/approvals",
  "/dashboard/mobile/devices",
  "/dashboard/approvals",
  "/dashboard/notification-center",
  "/dashboard/notification-center/list",
  "/dashboard/notification-center/preferences",
  "/dashboard/notification-center/templates",
  "/dashboard/notification-center/schedules",
  "/dashboard/tax",
  "/dashboard/tax/rules",
  "/dashboard/tax/regulatory",
  "/dashboard/tax/transactions",
  "/dashboard/production/orders",
  "/dashboard/production-execution/work-orders",
  "/dashboard/report-builder/catalog",
  "/dashboard/report-builder/builder",
  "/dashboard/report-builder/saved",
  "/dashboard/report-builder/viewer",
  "/dashboard/report-builder/dashboards",
  "/dashboard/report-builder/schedules",
  "/dashboard/chatter/feed",
  "/dashboard/chatter/search",
  "/dashboard/calendar/events",
  "/dashboard/calendar/view",
  "/dashboard/calendar/resources",
  "/dashboard/calendar/availability",
  "/dashboard/esign",
  "/dashboard/knowledge-base/articles",
  "/dashboard/finance/accounting/customers-ledger",
  "/dashboard/finance/accounting/suppliers-ledger",
  "/dashboard/finance/accounting/sales-invoices",
  "/dashboard/finance/accounting/purchase-invoices",
  "/dashboard/finance/accounting/payments",
  "/dashboard/bank-reconciliation/import",
  "/dashboard/bank-reconciliation/statements",
  "/dashboard/bank-reconciliation/open-items",
  "/dashboard/bank-reconciliation/balance",
  "/dashboard/bank-reconciliation/rules",
  "/dashboard/invoice-match/review-queue",
  "/dashboard/invoice-match/matches",
  "/dashboard/invoice-match/blocked",
  "/dashboard/invoice-match/duplicates",
  "/dashboard/fixed-assets/assets",
  "/dashboard/fixed-assets/categories",
  "/dashboard/fixed-assets/depreciation",
  "/dashboard/fixed-assets/posting",
  "/dashboard/fixed-assets/disposal",
  "/dashboard/fixed-assets/transfer",
  "/dashboard/fixed-assets/import",
  "/dashboard/dimensions/types",
  "/dashboard/dimensions/values",
  "/dashboard/dimensions/cost-centers",
  "/dashboard/dimensions/allocations",
  "/dashboard/dimensions/allocation-run",
  "/dashboard/dimensions/validation",
  "/dashboard/dimensions/defaults",
  "/dashboard/dimensions/reclassify",
  "/dashboard/dimensions/completeness",
  "/dashboard/dunning/aging",
  "/dashboard/dunning/workqueue",
  "/dashboard/dunning/credit-holds",
  "/dashboard/dunning/policies",
  "/dashboard/dunning/cases",
  "/dashboard/expenses/claims",
  "/dashboard/expenses/approval",
  "/dashboard/expenses/reimbursement",
  "/dashboard/expenses/advances",
  "/dashboard/expenses/categories",
  "/dashboard/expenses/policies",
  "/dashboard/recruitment/requisitions",
  "/dashboard/recruitment/candidates",
  "/dashboard/recruitment/pipeline",
  "/dashboard/recruitment/interviews",
  "/dashboard/recruitment/offers",
  "/dashboard/recruitment/stages",
  "/dashboard/ess/profile",
  "/dashboard/ess/leave",
  "/dashboard/ess/attendance",
  "/dashboard/ess/documents",
  "/dashboard/ess/requests",
  "/dashboard/ess/notifications",
  "/dashboard/ess/admin",
  "/dashboard/appraisals/periods",
  "/dashboard/appraisals/templates",
  "/dashboard/appraisals/records",
  "/dashboard/appraisals/self-review",
  "/dashboard/appraisals/manager-queue",
  "/dashboard/appraisals/hr-review",
  "/dashboard/appraisals/development-plans",
  "/dashboard/training/programs",
  "/dashboard/training/sessions",
  "/dashboard/training/skill-matrix",
  "/dashboard/training/assignments",
  "/dashboard/training/certifications",
  "/dashboard/training/feedback",
  "/dashboard/timesheets/my-timesheets",
  "/dashboard/timesheets/time-entry",
  "/dashboard/timesheets/weekly-view",
  "/dashboard/timesheets/approval-queue",
  "/dashboard/webhooks",
  "/dashboard/webhooks/definitions",
  "/dashboard/webhooks/subscriptions",
  "/dashboard/webhooks/deliveries",
  "/dashboard/webhooks/dead-letter",
  "/dashboard/webhooks/inbound",
  "/dashboard/developer/keys",
  "/dashboard/developer/graphql",
  "/dashboard/shelf-life/fefo-config",
  "/dashboard/shelf-life/lot-aging",
  "/dashboard/shelf-life/near-expiry",
  "/dashboard/shelf-life/expired",
  "/dashboard/shelf-life/retest-queue",
  "/dashboard/shelf-life/shipment-validation",
  "/dashboard/shelf-life/production-validation",
  "/dashboard/shelf-life/compliance",
  "/dashboard/shelf-life/disposition",
  "/dashboard/shelf-life/customer-rules",
  "/dashboard/shelf-life/bulk-hold-monitor",
  "/dashboard/traceability/recalls",
  "/dashboard/traceability/search",
  "/dashboard/traceability/backward",
  "/dashboard/traceability/forward",
  "/dashboard/traceability/genealogy",
  "/dashboard/traceability/mock-recall",
  "/dashboard/traceability/regulatory",
  "/dashboard/fleet/vehicles",
  "/dashboard/fleet/drivers",
  "/dashboard/fleet/trips",
  "/dashboard/fleet/fuel",
  "/dashboard/fleet/maintenance",
  "/dashboard/fleet/incidents",
  "/dashboard/marketing/crm",
  "/dashboard/marketing/crm/followup",
  "/dashboard/marketing/surveys",
  "/dashboard/marketing/surveys/new",
  "/dashboard/marketing/ecommerce/stores",
  "/dashboard/tpm/plans",
  "/dashboard/tpm/promotions",
  "/dashboard/tpm/calendar",
  "/dashboard/tpm/budget",
  "/dashboard/tpm/claims",
  "/dashboard/tpm/roi",
  "/dashboard/tpm/settlement",
  "/dashboard/mrp/forecast",
  "/dashboard/mrp/suggestions",
  "/dashboard/kanban/boards",
  "/dashboard/kanban/view",
  "/dashboard/kanban/cards",
  "/dashboard/procurement-suggestion/suggestions",
  "/dashboard/procurement-suggestion/groups",
  "/dashboard/procurement-suggestion/supplier-prices",
  "/dashboard/subcontracting/locations",
  "/dashboard/subcontracting/orders",
  "/dashboard/subcontracting/stock",
  "/dashboard/subcontracting/yield",
  "/dashboard/landed-cost/documents",
  "/dashboard/machine-ops/machines",
  "/dashboard/machine-ops/operators",
  "/dashboard/machine-ops/teams",
  "/dashboard/machine-ops/performance",
  "/dashboard/machine-ops/downtime",
  "/dashboard/machine-ops/costing",
  "/dashboard/machine-ops/certs",
  "/dashboard/machine-ops/assignment",
  "/dashboard/material-flow/issue",
  "/dashboard/material-flow/wip-transfer",
  "/dashboard/material-flow/bulk-transfer",
  "/dashboard/material-flow/fg-receipt",
  "/dashboard/material-flow/reservations",
  "/dashboard/material-flow/tanks",
  "/dashboard/material-flow/returns",
  "/dashboard/material-flow/reconciliation",
  "/dashboard/material-flow/history",
  "/dashboard/qms/inspections",
  "/dashboard/qms/templates",
  "/dashboard/qms/haccp",
  "/dashboard/qms/ccp",
  "/dashboard/qms/deviations",
  "/dashboard/qms/corrective-actions",
  "/dashboard/qms/quarantine",
  "/dashboard/qms/allergen",
  "/dashboard/allergen/material-profiles",
  "/dashboard/allergen/product-allergens",
  "/dashboard/allergen/change-logs",
  "/dashboard/price-lists/approval-queue",
  "/dashboard/contracts/list",
  "/dashboard/contracts/expiring",
  "/dashboard/recurring-orders/templates",
  "/dashboard/commissions/rules",
  "/dashboard/commissions/transactions",
  "/dashboard/commissions/payouts",
  "/dashboard/secondary-sales/analysis",
  "/dashboard/secondary-sales/inventory",
  "/dashboard/secondary-sales/upload",
  "/dashboard/van-sales/route",
  "/dashboard/van-sales/pos",
  "/dashboard/van-sales/stock",
  "/dashboard/van-sales/reconciliation",
  "/dashboard/van-sales/vans",
  "/dashboard/portal/accounts",
  "/dashboard/portal/drafts",
  "/dashboard/portal/claims",
  "/dashboard/portal/users",
  "/dashboard/portal/activity",
  "/dashboard/utility-management/kpi-center",
  "/dashboard/utility-management/kpi-center/electricity",
  "/dashboard/utility-management/kpi-center/water",
  "/dashboard/utility-management/kpi-center/soft-water",
  "/dashboard/utility-management/kpi-center/boiler",
  "/dashboard/utility-management/kpi-center/compressor",
  "/dashboard/utility-management/kpi-center/solar",
  "/dashboard/utility-management/kpi-center/chemicals",
  "/dashboard/utility-management/kpi-center/wastewater",
  "/dashboard/utility-management/kpi-center/utility-cost",
  "/dashboard/utility-management/kpi-center/machine-utility",
  "/dashboard/esg/activities",
  "/dashboard/esg/factors",
  "/dashboard/esg/targets",
  "/dashboard/esg/intelligence",
  // Wave 1C — AI and reports pages
  "/dashboard/custom-fields/ai",
  "/dashboard/reports/inventory",
  "/dashboard/reports/production",
  "/dashboard/reports/procurement",
  "/dashboard/reports/sales",
  "/dashboard/reports/finance",
  "/dashboard/reports/payments",
  "/dashboard/reports/marketing",
  "/dashboard/report-builder/ai",
  "/dashboard/chatter/reports",
  "/dashboard/chatter/ai",
  "/dashboard/notification-center/reports",
  "/dashboard/notification-center/ai",
  "/dashboard/bank-reconciliation/ai",
  "/dashboard/invoice-match/ai",
  "/dashboard/fixed-assets/ai",
  "/dashboard/dimensions/ai",
  "/dashboard/tax/reports",
  "/dashboard/expenses/reports",
  "/dashboard/expenses/ai",
  "/dashboard/recruitment/reports",
  "/dashboard/recruitment/ai",
  "/dashboard/ess/ai",
  "/dashboard/appraisals/reports",
  "/dashboard/appraisals/ai",
  "/dashboard/training/reports",
  "/dashboard/training/ai",
  "/dashboard/timesheets/reports",
  "/dashboard/timesheets/ai",
  "/dashboard/webhooks/reports",
  "/dashboard/fleet/reports",
  "/dashboard/tpm/ai",
  "/dashboard/kanban/reports",
  "/dashboard/kanban/ai",
  "/dashboard/procurement-suggestion/ai",
  "/dashboard/subcontracting/ai",
  "/dashboard/landed-cost/ai",
  "/dashboard/qms/reports",
  "/dashboard/qms/ai",
  "/dashboard/contracts/ai",
  "/dashboard/recurring-orders/reports",
  "/dashboard/recurring-orders/ai",
  "/dashboard/commissions/ai",
  "/dashboard/van-sales/ai",
  "/dashboard/portal/ai",
  "/dashboard/portal/reports",
  "/dashboard/utility-management/reports/daily-consumption",
  "/dashboard/utility-management/reports/equipment-efficiency",
  "/dashboard/utility-management/reports/treatment",
  "/dashboard/utility-management/reports/cost-allocation",
  "/dashboard/utility-management/reports/load-analysis",
  "/dashboard/utility-management/reports/anomalies",
  "/dashboard/utility-management/reports/sustainability",
  "/dashboard/esg/reports",
]);

function matchRedirect(pathname: string): { p: string; t?: string; d?: string } | null {
  // Real standalone pages bypass ALL redirects (exact and prefix)
  if (BYPASS_PREFIX_REDIRECT.has(pathname)) return null;

  // Exact match
  if (REDIRECTS[pathname]) return REDIRECTS[pathname];

  // Prefix match — longest prefix wins
  const parts = pathname.split("/");
  for (let i = parts.length - 1; i >= 2; i--) {
    const prefix = parts.slice(0, i).join("/");
    if (REDIRECTS[prefix]) return REDIRECTS[prefix];
  }
  return null;
}

export function middleware(request: NextRequest) {
  const { pathname, search } = request.nextUrl;

  // Auth guard: all /dashboard/* routes require the session cookie.
  // The cookie is HttpOnly so we can only check existence, not validity.
  // Full JWT verification still happens server-side on every API call.
  if (!request.cookies.has("erp_access_token")) {
    const loginUrl = new URL("/login", request.url);
    loginUrl.searchParams.set("next", pathname + search);
    return NextResponse.redirect(loginUrl, { status: 302 });
  }

  const match = matchRedirect(pathname);
  if (!match) return NextResponse.next();

  const params = new URLSearchParams(search);
  if (match.t) params.set("tab", match.t);
  if (match.d) params.set("drawer", match.d);

  const qs = params.toString();
  const dest = qs ? `${match.p}?${qs}` : match.p;

  return NextResponse.redirect(new URL(dest, request.url), { status: 302 });
}

export const config = {
  matcher: ["/dashboard/:path*"],
};
