/**
 * Legacy route → new workspace route redirects.
 * Key: old pathname (exact or prefix match)
 * Value: new pathname + search params
 *
 * Rules:
 * - Exact key matches take priority over prefix matches
 * - Child routes (with [id]) are handled by suffix-stripping to base path
 * - Add new entries when moving a page into a workspace tab
 */

export interface RedirectTarget {
  pathname: string;
  tab?: string;
  subtab?: string;
  drawer?: string;
}

/** Exact path redirects (highest priority) */
export const EXACT_REDIRECTS: Record<string, RedirectTarget> = {

  // ── Inventory ──────────────────────────────────────────────────────────────
  "/dashboard/movements":                       { pathname: "/dashboard/inventory", tab: "movements" },
  "/dashboard/cycle-count":                     { pathname: "/dashboard/inventory", tab: "cycle-count" },
  "/dashboard/cycle-count/plans":               { pathname: "/dashboard/inventory", tab: "cycle-count" },
  "/dashboard/cycle-count/tasks":               { pathname: "/dashboard/inventory", tab: "cycle-count" },
  "/dashboard/cycle-count/entries":             { pathname: "/dashboard/inventory", tab: "cycle-count" },
  "/dashboard/cycle-count/variances":           { pathname: "/dashboard/inventory", tab: "cycle-count" },
  "/dashboard/cycle-count/reports":             { pathname: "/dashboard/inventory", tab: "cycle-count" },
  "/dashboard/shelf-life":                      { pathname: "/dashboard/inventory", tab: "shelf-life" },
  "/dashboard/shelf-life/fefo-config":          { pathname: "/dashboard/inventory", tab: "shelf-life" },
  "/dashboard/shelf-life/lot-aging":            { pathname: "/dashboard/inventory", tab: "shelf-life" },
  "/dashboard/shelf-life/near-expiry":          { pathname: "/dashboard/inventory", tab: "shelf-life" },
  "/dashboard/shelf-life/expired":              { pathname: "/dashboard/inventory", tab: "shelf-life" },
  "/dashboard/shelf-life/retest-queue":         { pathname: "/dashboard/inventory", tab: "shelf-life" },
  "/dashboard/shelf-life/shipment-validation":  { pathname: "/dashboard/inventory", tab: "shelf-life" },
  "/dashboard/shelf-life/production-validation":{ pathname: "/dashboard/inventory", tab: "shelf-life" },
  "/dashboard/shelf-life/compliance":           { pathname: "/dashboard/inventory", tab: "shelf-life" },
  "/dashboard/shelf-life/disposition":          { pathname: "/dashboard/inventory", tab: "shelf-life" },
  "/dashboard/shelf-life/customer-rules":       { pathname: "/dashboard/inventory", tab: "shelf-life" },
  "/dashboard/shelf-life/bulk-hold-monitor":    { pathname: "/dashboard/inventory", tab: "shelf-life" },
  "/dashboard/traceability/search":             { pathname: "/dashboard/inventory", tab: "traceability" },
  "/dashboard/traceability/backward":           { pathname: "/dashboard/inventory", tab: "traceability" },
  "/dashboard/traceability/forward":            { pathname: "/dashboard/inventory", tab: "traceability" },
  "/dashboard/traceability/genealogy":          { pathname: "/dashboard/inventory", tab: "traceability" },
  "/dashboard/traceability/mock-recall":        { pathname: "/dashboard/inventory", tab: "traceability" },
  "/dashboard/traceability/templates":          { pathname: "/dashboard/inventory", tab: "traceability" },
  "/dashboard/traceability/regulatory":         { pathname: "/dashboard/inventory", tab: "traceability" },

  // ── Warehouses / WMS ───────────────────────────────────────────────────────
  "/dashboard/wms":                             { pathname: "/dashboard/warehouses", tab: "wms" },
  "/dashboard/wms/counts":                      { pathname: "/dashboard/warehouses", tab: "wms" },
  "/dashboard/wms/picking":                     { pathname: "/dashboard/warehouses", tab: "wms" },
  "/dashboard/wms/replenishment":               { pathname: "/dashboard/warehouses", tab: "wms" },
  "/dashboard/wms/reports":                     { pathname: "/dashboard/warehouses", tab: "wms" },
  "/dashboard/putaway":                         { pathname: "/dashboard/warehouses", tab: "wms" },
  "/dashboard/putaway/rules":                   { pathname: "/dashboard/warehouses", tab: "wms" },
  "/dashboard/containers":                      { pathname: "/dashboard/logistics", tab: "containers" },
  "/dashboard/containers/outstanding":          { pathname: "/dashboard/logistics", tab: "containers" },

  // ── Procurement ────────────────────────────────────────────────────────────
  "/dashboard/procurement-suggestion":                          { pathname: "/dashboard/procurement", tab: "suggestions" },
  "/dashboard/procurement-suggestion/suggestions":              { pathname: "/dashboard/procurement", tab: "suggestions" },
  "/dashboard/procurement-suggestion/groups":                   { pathname: "/dashboard/procurement", tab: "suggestions" },
  "/dashboard/procurement-suggestion/supplier-prices":          { pathname: "/dashboard/procurement", tab: "suggestions" },
  "/dashboard/procurement-suggestion/supplier-compare":         { pathname: "/dashboard/procurement", tab: "suggestions" },
  "/dashboard/procurement-suggestion/reports":                  { pathname: "/dashboard/procurement", tab: "suggestions" },
  "/dashboard/procurement-suggestion/ai":                       { pathname: "/dashboard/procurement", tab: "suggestions" },
  "/dashboard/subcontracting":                  { pathname: "/dashboard/procurement", tab: "subcontracting" },
  "/dashboard/subcontracting/orders":           { pathname: "/dashboard/procurement", tab: "subcontracting" },
  "/dashboard/subcontracting/locations":        { pathname: "/dashboard/procurement", tab: "subcontracting" },
  "/dashboard/subcontracting/stock":            { pathname: "/dashboard/procurement", tab: "subcontracting" },
  "/dashboard/subcontracting/yield":            { pathname: "/dashboard/procurement", tab: "subcontracting" },
  "/dashboard/subcontracting/performance":      { pathname: "/dashboard/procurement", tab: "subcontracting" },
  "/dashboard/subcontracting/ai":               { pathname: "/dashboard/procurement", tab: "subcontracting" },
  "/dashboard/copacking":                       { pathname: "/dashboard/procurement", tab: "subcontracting" },
  "/dashboard/landed-cost/documents":           { pathname: "/dashboard/procurement", tab: "landed-cost" },
  "/dashboard/landed-cost/new":                 { pathname: "/dashboard/procurement", tab: "landed-cost", drawer: "create" },
  "/dashboard/landed-cost/reports":             { pathname: "/dashboard/procurement", tab: "landed-cost" },
  "/dashboard/landed-cost/ai":                  { pathname: "/dashboard/procurement", tab: "landed-cost" },
  "/dashboard/supplier-portal/eta":             { pathname: "/dashboard/procurement", tab: "supplier-portal" },
  "/dashboard/supplier-portal/documents":       { pathname: "/dashboard/procurement", tab: "supplier-portal" },
  "/dashboard/supplier-portal/invoices":        { pathname: "/dashboard/procurement", tab: "supplier-portal" },
  "/dashboard/supplier-portal/payment":         { pathname: "/dashboard/procurement", tab: "supplier-portal" },
  "/dashboard/supplier-portal/users":           { pathname: "/dashboard/procurement", tab: "supplier-portal" },
  "/dashboard/supplier-portal/activity":        { pathname: "/dashboard/procurement", tab: "supplier-portal" },
  "/dashboard/supplier-portal/reports":         { pathname: "/dashboard/procurement", tab: "supplier-portal" },
  "/dashboard/supplier-portal/ai":              { pathname: "/dashboard/procurement", tab: "supplier-portal" },

  // ── Sales ──────────────────────────────────────────────────────────────────
  "/dashboard/price-lists/approval-queue":      { pathname: "/dashboard/sales", tab: "price-lists" },
  "/dashboard/price-lists/discount-rules":      { pathname: "/dashboard/sales", tab: "price-lists" },
  "/dashboard/price-lists/margin":              { pathname: "/dashboard/sales", tab: "price-lists" },
  "/dashboard/price-lists/compare":             { pathname: "/dashboard/sales", tab: "price-lists" },
  "/dashboard/price-lists/import":              { pathname: "/dashboard/sales", tab: "price-lists" },
  "/dashboard/price-lists/reports":             { pathname: "/dashboard/sales", tab: "price-lists" },
  "/dashboard/price-lists/ai":                  { pathname: "/dashboard/sales", tab: "price-lists" },
  "/dashboard/dynamic-pricing":                 { pathname: "/dashboard/sales", tab: "dynamic-pricing" },
  "/dashboard/contracts/new":                   { pathname: "/dashboard/sales", tab: "contracts", drawer: "create" },
  "/dashboard/contracts/expiring":              { pathname: "/dashboard/sales", tab: "contracts" },
  "/dashboard/contracts/performance":           { pathname: "/dashboard/sales", tab: "contracts" },
  "/dashboard/contracts/reports":               { pathname: "/dashboard/sales", tab: "contracts" },
  "/dashboard/contracts/ai":                    { pathname: "/dashboard/sales", tab: "contracts" },
  "/dashboard/recurring-orders/billing":        { pathname: "/dashboard/sales", tab: "recurring" },
  "/dashboard/recurring-orders/schedule":       { pathname: "/dashboard/sales", tab: "recurring" },
  "/dashboard/recurring-orders/upcoming-demand":{ pathname: "/dashboard/sales", tab: "recurring" },
  "/dashboard/recurring-orders/generation-log": { pathname: "/dashboard/sales", tab: "recurring" },
  "/dashboard/recurring-orders/pause-skip":     { pathname: "/dashboard/sales", tab: "recurring" },
  "/dashboard/recurring-orders/reports":        { pathname: "/dashboard/sales", tab: "recurring" },
  "/dashboard/recurring-orders/ai":             { pathname: "/dashboard/sales", tab: "recurring" },
  "/dashboard/commissions":                     { pathname: "/dashboard/sales", tab: "commissions" },
  "/dashboard/commissions/rules":               { pathname: "/dashboard/sales", tab: "commissions" },
  "/dashboard/commissions/transactions":        { pathname: "/dashboard/sales", tab: "commissions" },
  "/dashboard/commissions/targets":             { pathname: "/dashboard/sales", tab: "commissions" },
  "/dashboard/commissions/payouts":             { pathname: "/dashboard/sales", tab: "commissions" },
  "/dashboard/commissions/reports":             { pathname: "/dashboard/sales", tab: "commissions" },
  "/dashboard/commissions/ai":                  { pathname: "/dashboard/sales", tab: "commissions" },
  "/dashboard/van-sales/vans/new":              { pathname: "/dashboard/sales", tab: "van-sales", drawer: "create" },
  "/dashboard/van-sales/route":                 { pathname: "/dashboard/sales", tab: "van-sales" },
  "/dashboard/van-sales/pos":                   { pathname: "/dashboard/sales", tab: "van-sales" },
  "/dashboard/van-sales/stock":                 { pathname: "/dashboard/sales", tab: "van-sales" },
  "/dashboard/van-sales/reconciliation":        { pathname: "/dashboard/sales", tab: "van-sales" },
  "/dashboard/van-sales/reports":               { pathname: "/dashboard/sales", tab: "van-sales" },
  "/dashboard/van-sales/ai":                    { pathname: "/dashboard/sales", tab: "van-sales" },
  "/dashboard/van-sales/fraud":                 { pathname: "/dashboard/sales", tab: "van-sales" },
  "/dashboard/van-sales/performance":           { pathname: "/dashboard/sales", tab: "van-sales" },
  "/dashboard/van-sales/mpesa":                 { pathname: "/dashboard/sales", tab: "van-sales" },
  "/dashboard/van-sales/field-rep":             { pathname: "/dashboard/sales", tab: "van-sales" },
  "/dashboard/van-sales/route-optimizer":       { pathname: "/dashboard/sales", tab: "van-sales" },
  "/dashboard/van-sales/returns":               { pathname: "/dashboard/sales", tab: "van-sales" },
  "/dashboard/van-sales/visits":                { pathname: "/dashboard/sales", tab: "van-sales" },
  "/dashboard/sales/pod":                       { pathname: "/dashboard/sales", tab: "delivery" },
  "/dashboard/sales/customer-statement":        { pathname: "/dashboard/sales", tab: "customers" },
  "/dashboard/portal/order-tracking":           { pathname: "/dashboard/sales", tab: "portal" },
  "/dashboard/portal/sell-through":             { pathname: "/dashboard/sales", tab: "portal" },
  "/dashboard/portal/drafts":                   { pathname: "/dashboard/sales", tab: "portal" },
  "/dashboard/portal/claims":                   { pathname: "/dashboard/sales", tab: "portal" },
  "/dashboard/portal/users":                    { pathname: "/dashboard/sales", tab: "portal" },
  "/dashboard/portal/activity":                 { pathname: "/dashboard/sales", tab: "portal" },
  "/dashboard/portal/reports":                  { pathname: "/dashboard/sales", tab: "portal" },
  "/dashboard/portal/ai":                       { pathname: "/dashboard/sales", tab: "portal" },

  // ── CRM ───────────────────────────────────────────────────────────────────
  "/dashboard/crm/ai":                          { pathname: "/dashboard/crm", tab: "overview" },
  "/dashboard/crm/overdue":                     { pathname: "/dashboard/crm", tab: "pipeline" },
  "/dashboard/crm/qualify":                     { pathname: "/dashboard/crm", tab: "leads" },
  "/dashboard/loyalty":                         { pathname: "/dashboard/crm", tab: "loyalty" },
  "/dashboard/nps":                             { pathname: "/dashboard/crm", tab: "nps" },
  "/dashboard/surveys/new":                     { pathname: "/dashboard/crm", tab: "surveys", drawer: "create" },

  // ── Marketing ─────────────────────────────────────────────────────────────
  "/dashboard/tpm/calendar":                    { pathname: "/dashboard/marketing", tab: "tpm" },
  "/dashboard/tpm/plans":                       { pathname: "/dashboard/marketing", tab: "tpm" },
  "/dashboard/tpm/budget":                      { pathname: "/dashboard/marketing", tab: "tpm" },
  "/dashboard/tpm/claims":                      { pathname: "/dashboard/marketing", tab: "tpm" },
  "/dashboard/tpm/settlement":                  { pathname: "/dashboard/marketing", tab: "tpm" },
  "/dashboard/tpm/roi":                         { pathname: "/dashboard/marketing", tab: "tpm" },
  "/dashboard/tpm/ai":                          { pathname: "/dashboard/marketing", tab: "tpm" },
  "/dashboard/promotions":                      { pathname: "/dashboard/marketing", tab: "promotions-schemes" },
  "/dashboard/promotions/schemes":              { pathname: "/dashboard/marketing", tab: "promotions-schemes" },
  "/dashboard/promotions/simulate":             { pathname: "/dashboard/marketing", tab: "promotions-schemes" },
  "/dashboard/promotions/overrides":            { pathname: "/dashboard/marketing", tab: "promotions-schemes" },
  "/dashboard/promotions/analytics":            { pathname: "/dashboard/marketing", tab: "promotions-schemes" },
  "/dashboard/promotions/ai":                   { pathname: "/dashboard/marketing", tab: "promotions-schemes" },
  "/dashboard/market-intelligence":             { pathname: "/dashboard/marketing", tab: "market-intel" },
  // Marketing workspace child routes (no [id] sub-routes remain)
  "/dashboard/marketing/ecommerce":             { pathname: "/dashboard/marketing", tab: "ecommerce" },
  "/dashboard/marketing/ai-optimizer":          { pathname: "/dashboard/marketing", tab: "analytics" },

  // ── Finance ───────────────────────────────────────────────────────────────
  "/dashboard/finance/accounting":              { pathname: "/dashboard/finance", tab: "accounting" },
  "/dashboard/bank-reconciliation/import":      { pathname: "/dashboard/finance", tab: "bank-recon" },
  "/dashboard/bank-reconciliation/accounts":    { pathname: "/dashboard/finance", tab: "bank-recon" },
  "/dashboard/bank-reconciliation/open-items":  { pathname: "/dashboard/finance", tab: "bank-recon" },
  "/dashboard/bank-reconciliation/rules":       { pathname: "/dashboard/finance", tab: "bank-recon" },
  "/dashboard/bank-reconciliation/balance":     { pathname: "/dashboard/finance", tab: "bank-recon" },
  "/dashboard/bank-reconciliation/mpesa":       { pathname: "/dashboard/finance", tab: "bank-recon" },
  "/dashboard/bank-reconciliation/reports":     { pathname: "/dashboard/finance", tab: "bank-recon" },
  "/dashboard/bank-reconciliation/ai":          { pathname: "/dashboard/finance", tab: "bank-recon" },
  "/dashboard/invoice-match/matches":           { pathname: "/dashboard/finance", tab: "invoice-match" },
  "/dashboard/invoice-match/review-queue":      { pathname: "/dashboard/finance", tab: "invoice-match" },
  "/dashboard/invoice-match/blocked":           { pathname: "/dashboard/finance", tab: "invoice-match" },
  "/dashboard/invoice-match/duplicates":        { pathname: "/dashboard/finance", tab: "invoice-match" },
  "/dashboard/invoice-match/tolerance-rules":   { pathname: "/dashboard/finance", tab: "invoice-match" },
  "/dashboard/invoice-match/reports":           { pathname: "/dashboard/finance", tab: "invoice-match" },
  "/dashboard/invoice-match/ai":                { pathname: "/dashboard/finance", tab: "invoice-match" },
  "/dashboard/fixed-assets":                    { pathname: "/dashboard/finance", tab: "fixed-assets" },
  "/dashboard/fixed-assets/assets":             { pathname: "/dashboard/finance", tab: "fixed-assets" },
  "/dashboard/fixed-assets/assets/new":         { pathname: "/dashboard/finance", tab: "fixed-assets", drawer: "create" },
  "/dashboard/fixed-assets/categories":         { pathname: "/dashboard/finance", tab: "fixed-assets" },
  "/dashboard/fixed-assets/depreciation":       { pathname: "/dashboard/finance", tab: "fixed-assets" },
  "/dashboard/fixed-assets/posting":            { pathname: "/dashboard/finance", tab: "fixed-assets" },
  "/dashboard/fixed-assets/disposal":           { pathname: "/dashboard/finance", tab: "fixed-assets" },
  "/dashboard/fixed-assets/transfer":           { pathname: "/dashboard/finance", tab: "fixed-assets" },
  "/dashboard/fixed-assets/import":             { pathname: "/dashboard/finance", tab: "fixed-assets" },
  "/dashboard/fixed-assets/ai":                 { pathname: "/dashboard/finance", tab: "fixed-assets" },
  "/dashboard/dimensions":                      { pathname: "/dashboard/finance", tab: "dimensions" },
  "/dashboard/dimensions/types":                { pathname: "/dashboard/finance", tab: "dimensions" },
  "/dashboard/dimensions/values":               { pathname: "/dashboard/finance", tab: "dimensions" },
  "/dashboard/dimensions/cost-centers":         { pathname: "/dashboard/finance", tab: "dimensions" },
  "/dashboard/dimensions/allocations":          { pathname: "/dashboard/finance", tab: "dimensions" },
  "/dashboard/dimensions/allocation-run":       { pathname: "/dashboard/finance", tab: "dimensions" },
  "/dashboard/dimensions/validation":           { pathname: "/dashboard/finance", tab: "dimensions" },
  "/dashboard/dimensions/defaults":             { pathname: "/dashboard/finance", tab: "dimensions" },
  "/dashboard/dimensions/reclassify":           { pathname: "/dashboard/finance", tab: "dimensions" },
  "/dashboard/dimensions/completeness":         { pathname: "/dashboard/finance", tab: "dimensions" },
  "/dashboard/dimensions/ai":                   { pathname: "/dashboard/finance", tab: "dimensions" },
  "/dashboard/dunning/aging":                   { pathname: "/dashboard/finance", tab: "dunning" },
  "/dashboard/dunning/workqueue":               { pathname: "/dashboard/finance", tab: "dunning" },
  "/dashboard/dunning/credit-holds":            { pathname: "/dashboard/finance", tab: "dunning" },
  "/dashboard/dunning/policies":                { pathname: "/dashboard/finance", tab: "dunning" },
  "/dashboard/dunning/templates":               { pathname: "/dashboard/finance", tab: "dunning" },
  "/dashboard/dunning/reports":                 { pathname: "/dashboard/finance", tab: "dunning" },
  "/dashboard/dunning/ai":                      { pathname: "/dashboard/finance", tab: "dunning" },
  "/dashboard/tax":                             { pathname: "/dashboard/finance", tab: "tax" },
  "/dashboard/tax/rules":                       { pathname: "/dashboard/finance", tab: "tax" },
  "/dashboard/tax/regulatory":                  { pathname: "/dashboard/finance", tab: "tax" },
  "/dashboard/tax/transactions":                { pathname: "/dashboard/finance", tab: "tax" },
  "/dashboard/tax/reports":                     { pathname: "/dashboard/finance", tab: "tax" },
  "/dashboard/bank-api":                        { pathname: "/dashboard/finance", tab: "bank-api" },
  "/dashboard/expenses":                        { pathname: "/dashboard/hr", tab: "expenses" },
  "/dashboard/expenses/claims":                 { pathname: "/dashboard/hr", tab: "expenses" },
  "/dashboard/expenses/claims/new":             { pathname: "/dashboard/hr", tab: "expenses", drawer: "create" },
  "/dashboard/expenses/approval":               { pathname: "/dashboard/hr", tab: "expenses" },
  "/dashboard/expenses/reimbursement":          { pathname: "/dashboard/hr", tab: "expenses" },
  "/dashboard/expenses/advances":               { pathname: "/dashboard/hr", tab: "expenses" },
  "/dashboard/expenses/categories":             { pathname: "/dashboard/hr", tab: "expenses" },
  "/dashboard/expenses/policies":               { pathname: "/dashboard/hr", tab: "expenses" },
  "/dashboard/expenses/receipt-ocr":            { pathname: "/dashboard/hr", tab: "expenses" },
  "/dashboard/expenses/reports":                { pathname: "/dashboard/hr", tab: "expenses" },
  "/dashboard/expenses/ai":                     { pathname: "/dashboard/hr", tab: "expenses" },

  // ── Production ─────────────────────────────────────────────────────────────
  // Production workspace child routes
  "/dashboard/production/advanced":             { pathname: "/dashboard/production", tab: "scheduling" },
  "/dashboard/production/ai":                   { pathname: "/dashboard/production", tab: "plans" },
  "/dashboard/production/plans":                { pathname: "/dashboard/production", tab: "plans" },
  "/dashboard/production/shifts":               { pathname: "/dashboard/production", tab: "scheduling" },
  "/dashboard/production/work-orders":          { pathname: "/dashboard/production", tab: "orders" },
  "/dashboard/production-execution/work-orders":{ pathname: "/dashboard/production", tab: "execution" },
  "/dashboard/machine-ops":                     { pathname: "/dashboard/production", tab: "machine-ops" },
  "/dashboard/machine-ops/machines":            { pathname: "/dashboard/production", tab: "machine-ops" },
  "/dashboard/machine-ops/operators":           { pathname: "/dashboard/production", tab: "machine-ops" },
  "/dashboard/machine-ops/teams":               { pathname: "/dashboard/production", tab: "machine-ops" },
  "/dashboard/machine-ops/runtime":             { pathname: "/dashboard/production", tab: "machine-ops" },
  "/dashboard/machine-ops/performance":         { pathname: "/dashboard/production", tab: "machine-ops" },
  "/dashboard/machine-ops/downtime":            { pathname: "/dashboard/production", tab: "machine-ops" },
  "/dashboard/machine-ops/costing":             { pathname: "/dashboard/production", tab: "machine-ops" },
  "/dashboard/machine-ops/certs":               { pathname: "/dashboard/production", tab: "machine-ops" },
  "/dashboard/machine-ops/assignment":          { pathname: "/dashboard/production", tab: "machine-ops" },
  "/dashboard/material-flow":                   { pathname: "/dashboard/production", tab: "material-flow" },
  "/dashboard/material-flow/issue":             { pathname: "/dashboard/production", tab: "material-flow" },
  "/dashboard/material-flow/reservations":      { pathname: "/dashboard/production", tab: "material-flow" },
  "/dashboard/material-flow/wip-transfer":      { pathname: "/dashboard/production", tab: "material-flow" },
  "/dashboard/material-flow/bulk-transfer":     { pathname: "/dashboard/production", tab: "material-flow" },
  "/dashboard/material-flow/packaging":         { pathname: "/dashboard/production", tab: "material-flow" },
  "/dashboard/material-flow/fg-receipt":        { pathname: "/dashboard/production", tab: "material-flow" },
  "/dashboard/material-flow/returns":           { pathname: "/dashboard/production", tab: "material-flow" },
  "/dashboard/material-flow/tanks":             { pathname: "/dashboard/production", tab: "material-flow" },
  "/dashboard/material-flow/history":           { pathname: "/dashboard/production", tab: "material-flow" },
  "/dashboard/material-flow/reconciliation":    { pathname: "/dashboard/production", tab: "material-flow" },
  "/dashboard/material-flow/stages":            { pathname: "/dashboard/production", tab: "material-flow" },
  "/dashboard/projects/dashboard":              { pathname: "/dashboard/production", tab: "projects" },

  // ── Planning ───────────────────────────────────────────────────────────────
  "/dashboard/mrp":                             { pathname: "/dashboard/planning", tab: "mrp" },
  "/dashboard/mrp/workbench":                   { pathname: "/dashboard/planning", tab: "mrp" },
  "/dashboard/mrp/run":                         { pathname: "/dashboard/planning", tab: "mrp" },
  "/dashboard/mrp/suggestions":                 { pathname: "/dashboard/planning", tab: "mrp" },
  "/dashboard/mrp/forecast":                    { pathname: "/dashboard/planning", tab: "mrp" },
  "/dashboard/mrp/forecast/accuracy":           { pathname: "/dashboard/planning", tab: "mrp" },
  "/dashboard/mrp/forecast/correlation":        { pathname: "/dashboard/planning", tab: "mrp" },
  "/dashboard/mps":                             { pathname: "/dashboard/planning", tab: "mps" },
  // Note: mps/planning-board, mps/capacity, mps/campaigns, mps/whatif are real standalone pages — no redirect
  // NOTE: /dashboard/planning itself is the workspace — no self-redirect (would loop).
  // Child routes redirect to specific tabs:
  "/dashboard/planning/schedule":               { pathname: "/dashboard/planning", tab: "advanced" },
  "/dashboard/planning/capacity":               { pathname: "/dashboard/planning", tab: "advanced" },
  "/dashboard/planning/bottlenecks":            { pathname: "/dashboard/planning", tab: "advanced" },
  "/dashboard/planning/simulation":             { pathname: "/dashboard/planning", tab: "advanced" },
  "/dashboard/planning/changeover":             { pathname: "/dashboard/planning", tab: "advanced" },
  "/dashboard/kanban":                          { pathname: "/dashboard/planning", tab: "kanban" },
  "/dashboard/kanban/boards":                   { pathname: "/dashboard/planning", tab: "kanban" },
  "/dashboard/kanban/view":                     { pathname: "/dashboard/planning", tab: "kanban" },
  "/dashboard/kanban/cards":                    { pathname: "/dashboard/planning", tab: "kanban" },
  "/dashboard/kanban/reports":                  { pathname: "/dashboard/planning", tab: "kanban" },
  "/dashboard/kanban/ai":                       { pathname: "/dashboard/planning", tab: "kanban" },

  // ── Quality ────────────────────────────────────────────────────────────────
  "/dashboard/qms":                             { pathname: "/dashboard/quality", tab: "qms" },
  "/dashboard/qms/inspections":                 { pathname: "/dashboard/quality", tab: "inspections" },
  "/dashboard/qms/templates":                   { pathname: "/dashboard/quality", tab: "qms" },
  "/dashboard/qms/haccp":                       { pathname: "/dashboard/quality", tab: "qms" },
  "/dashboard/qms/ccp":                         { pathname: "/dashboard/quality", tab: "qms" },
  "/dashboard/qms/deviations":                  { pathname: "/dashboard/quality", tab: "qms" },
  "/dashboard/qms/corrective-actions":          { pathname: "/dashboard/quality", tab: "qms" },
  "/dashboard/qms/quarantine":                  { pathname: "/dashboard/quality", tab: "qms" },
  "/dashboard/qms/allergen":                    { pathname: "/dashboard/quality", tab: "allergen" },
  "/dashboard/qms/calibration":                 { pathname: "/dashboard/quality", tab: "qms" },
  "/dashboard/qms/aql":                         { pathname: "/dashboard/quality", tab: "qms" },
  "/dashboard/qms/coa":                         { pathname: "/dashboard/quality", tab: "qms" },
  "/dashboard/qms/audit-checklists":            { pathname: "/dashboard/quality", tab: "qms" },
  "/dashboard/qms/supplier-safety":             { pathname: "/dashboard/quality", tab: "qms" },
  "/dashboard/qms/reports":                     { pathname: "/dashboard/quality", tab: "reports" },
  "/dashboard/qms/ai":                          { pathname: "/dashboard/quality", tab: "qms" },
  "/dashboard/allergen":                        { pathname: "/dashboard/quality", tab: "allergen" },
  "/dashboard/allergen/allergens":              { pathname: "/dashboard/quality", tab: "allergen" },
  "/dashboard/allergen/material-profiles":      { pathname: "/dashboard/quality", tab: "allergen" },
  "/dashboard/allergen/nutrition":              { pathname: "/dashboard/quality", tab: "allergen" },
  "/dashboard/allergen/product-allergens":      { pathname: "/dashboard/quality", tab: "allergen" },
  "/dashboard/allergen/product-nutrition":      { pathname: "/dashboard/quality", tab: "allergen" },
  "/dashboard/allergen/rollup":                 { pathname: "/dashboard/quality", tab: "allergen" },
  "/dashboard/allergen/label-readiness":        { pathname: "/dashboard/quality", tab: "allergen" },
  "/dashboard/allergen/cleaning":               { pathname: "/dashboard/quality", tab: "allergen" },
  "/dashboard/allergen/change-logs":            { pathname: "/dashboard/quality", tab: "allergen" },
  "/dashboard/allergen/reports":                { pathname: "/dashboard/quality", tab: "allergen" },
  "/dashboard/allergen/ai":                     { pathname: "/dashboard/quality", tab: "allergen" },
  "/dashboard/quality/consumer-complaints":     { pathname: "/dashboard/quality", tab: "consumer-complaints" },

  // ── Compliance ─────────────────────────────────────────────────────────────
  "/dashboard/gs1":                             { pathname: "/dashboard/compliance", tab: "gs1" },
  "/dashboard/gs1/config":                      { pathname: "/dashboard/compliance", tab: "gs1" },
  "/dashboard/gs1/barcodes":                    { pathname: "/dashboard/compliance", tab: "gs1" },
  "/dashboard/gs1/labels":                      { pathname: "/dashboard/compliance", tab: "gs1" },
  "/dashboard/gs1/print-queue":                 { pathname: "/dashboard/compliance", tab: "gs1" },
  "/dashboard/gs1/sscc":                        { pathname: "/dashboard/compliance", tab: "gs1" },
  "/dashboard/gs1/scan":                        { pathname: "/dashboard/compliance", tab: "gs1" },
  "/dashboard/gs1/reports":                     { pathname: "/dashboard/compliance", tab: "gs1" },
  "/dashboard/gs1/ai":                          { pathname: "/dashboard/compliance", tab: "gs1" },

  // ── Utilities ──────────────────────────────────────────────────────────────
  "/dashboard/iot":                             { pathname: "/dashboard/utility-management", tab: "iot" },
  "/dashboard/esg":                             { pathname: "/dashboard/utility-management", tab: "esg" },
  // Utility-management workspace child routes
  "/dashboard/utility-management/categories":   { pathname: "/dashboard/utility-management", tab: "assets" },
  "/dashboard/utility-management/kpi-center":   { pathname: "/dashboard/utility-management", tab: "kpi-center" },
  "/dashboard/utility-management/reports":      { pathname: "/dashboard/utility-management", tab: "reports" },
  "/dashboard/esg/activities":                  { pathname: "/dashboard/utility-management", tab: "esg" },
  "/dashboard/esg/factors":                     { pathname: "/dashboard/utility-management", tab: "esg" },
  "/dashboard/esg/carbon":                      { pathname: "/dashboard/utility-management", tab: "esg" },
  "/dashboard/esg/intelligence":                { pathname: "/dashboard/utility-management", tab: "esg" },
  "/dashboard/esg/targets":                     { pathname: "/dashboard/utility-management", tab: "esg" },
  "/dashboard/esg/reports":                     { pathname: "/dashboard/utility-management", tab: "esg" },

  // ── Logistics ─────────────────────────────────────────────────────────────
  "/dashboard/fleet":                           { pathname: "/dashboard/logistics", tab: "fleet" },
  "/dashboard/fleet/vehicles":                  { pathname: "/dashboard/logistics", tab: "fleet" },
  "/dashboard/fleet/drivers":                   { pathname: "/dashboard/logistics", tab: "fleet" },
  "/dashboard/fleet/trips":                     { pathname: "/dashboard/logistics", tab: "fleet" },
  "/dashboard/fleet/fuel":                      { pathname: "/dashboard/logistics", tab: "fleet" },
  "/dashboard/fleet/maintenance":               { pathname: "/dashboard/logistics", tab: "fleet" },
  "/dashboard/fleet/incidents":                 { pathname: "/dashboard/logistics", tab: "fleet" },
  "/dashboard/fleet/reports":                   { pathname: "/dashboard/logistics", tab: "fleet" },
  "/dashboard/logistics/containers":            { pathname: "/dashboard/logistics", tab: "containers" },

  // ── HR ─────────────────────────────────────────────────────────────────────
  "/dashboard/recruitment":                     { pathname: "/dashboard/hr", tab: "recruitment" },
  "/dashboard/recruitment/requisitions":        { pathname: "/dashboard/hr", tab: "recruitment" },
  "/dashboard/recruitment/requisitions/new":    { pathname: "/dashboard/hr", tab: "recruitment", drawer: "create" },
  "/dashboard/recruitment/candidates":          { pathname: "/dashboard/hr", tab: "recruitment" },
  "/dashboard/recruitment/candidates/new":      { pathname: "/dashboard/hr", tab: "recruitment", drawer: "create" },
  "/dashboard/recruitment/pipeline":            { pathname: "/dashboard/hr", tab: "recruitment" },
  "/dashboard/recruitment/interviews":          { pathname: "/dashboard/hr", tab: "recruitment" },
  "/dashboard/recruitment/offers":              { pathname: "/dashboard/hr", tab: "recruitment" },
  "/dashboard/recruitment/stages":              { pathname: "/dashboard/hr", tab: "recruitment" },
  "/dashboard/recruitment/reports":             { pathname: "/dashboard/hr", tab: "recruitment" },
  "/dashboard/recruitment/ai":                  { pathname: "/dashboard/hr", tab: "recruitment" },
  "/dashboard/ess":                             { pathname: "/dashboard/hr", tab: "ess" },
  "/dashboard/ess/profile":                     { pathname: "/dashboard/hr", tab: "ess" },
  "/dashboard/ess/leave":                       { pathname: "/dashboard/hr", tab: "ess" },
  "/dashboard/ess/attendance":                  { pathname: "/dashboard/hr", tab: "ess" },
  "/dashboard/ess/documents":                   { pathname: "/dashboard/hr", tab: "ess" },
  "/dashboard/ess/requests":                    { pathname: "/dashboard/hr", tab: "ess" },
  "/dashboard/ess/notifications":               { pathname: "/dashboard/hr", tab: "ess" },
  "/dashboard/ess/admin":                       { pathname: "/dashboard/hr", tab: "ess" },
  "/dashboard/ess/ai":                          { pathname: "/dashboard/hr", tab: "ess" },
  "/dashboard/appraisals":                      { pathname: "/dashboard/hr", tab: "appraisals" },
  "/dashboard/appraisals/periods":              { pathname: "/dashboard/hr", tab: "appraisals" },
  "/dashboard/appraisals/templates":            { pathname: "/dashboard/hr", tab: "appraisals" },
  "/dashboard/appraisals/records":              { pathname: "/dashboard/hr", tab: "appraisals" },
  "/dashboard/appraisals/records/new":          { pathname: "/dashboard/hr", tab: "appraisals", drawer: "create" },
  "/dashboard/appraisals/self-review":          { pathname: "/dashboard/hr", tab: "appraisals" },
  "/dashboard/appraisals/manager-queue":        { pathname: "/dashboard/hr", tab: "appraisals" },
  "/dashboard/appraisals/hr-review":            { pathname: "/dashboard/hr", tab: "appraisals" },
  "/dashboard/appraisals/development-plans":    { pathname: "/dashboard/hr", tab: "appraisals" },
  "/dashboard/appraisals/reports":              { pathname: "/dashboard/hr", tab: "appraisals" },
  "/dashboard/appraisals/ai":                   { pathname: "/dashboard/hr", tab: "appraisals" },
  "/dashboard/training":                        { pathname: "/dashboard/hr", tab: "training" },
  "/dashboard/training/programs":               { pathname: "/dashboard/hr", tab: "training" },
  "/dashboard/training/sessions":               { pathname: "/dashboard/hr", tab: "training" },
  "/dashboard/training/skill-matrix":           { pathname: "/dashboard/hr", tab: "training" },
  "/dashboard/training/assignments":            { pathname: "/dashboard/hr", tab: "training" },
  "/dashboard/training/certifications":         { pathname: "/dashboard/hr", tab: "training" },
  "/dashboard/training/feedback":               { pathname: "/dashboard/hr", tab: "training" },
  "/dashboard/training/reports":                { pathname: "/dashboard/hr", tab: "training" },
  "/dashboard/training/ai":                     { pathname: "/dashboard/hr", tab: "training" },
  "/dashboard/timesheets":                      { pathname: "/dashboard/hr", tab: "timesheets" },
  "/dashboard/timesheets/my-timesheets":        { pathname: "/dashboard/hr", tab: "timesheets" },
  "/dashboard/timesheets/time-entry":           { pathname: "/dashboard/hr", tab: "timesheets" },
  "/dashboard/timesheets/weekly-view":          { pathname: "/dashboard/hr", tab: "timesheets" },
  "/dashboard/timesheets/approval-queue":       { pathname: "/dashboard/hr", tab: "timesheets" },
  "/dashboard/timesheets/reports":              { pathname: "/dashboard/hr", tab: "timesheets" },
  "/dashboard/timesheets/ai":                   { pathname: "/dashboard/hr", tab: "timesheets" },

  // ── Documents ─────────────────────────────────────────────────────────────
  "/dashboard/documents/new":                   { pathname: "/dashboard/documents", drawer: "create" },
  "/dashboard/knowledge-base/articles":         { pathname: "/dashboard/documents", tab: "knowledge-base" },
  "/dashboard/esign":                           { pathname: "/dashboard/documents", tab: "esign" },

  // ── Communication ─────────────────────────────────────────────────────────
  "/dashboard/chatter":                         { pathname: "/dashboard/communication", tab: "chatter" },
  "/dashboard/chatter/feed":                    { pathname: "/dashboard/communication", tab: "chatter" },
  "/dashboard/chatter/threads":                 { pathname: "/dashboard/communication", tab: "chatter" },
  "/dashboard/chatter/search":                  { pathname: "/dashboard/communication", tab: "chatter" },
  "/dashboard/chatter/reports":                 { pathname: "/dashboard/communication", tab: "chatter" },
  "/dashboard/chatter/ai":                      { pathname: "/dashboard/communication", tab: "chatter" },
  "/dashboard/calendar":                        { pathname: "/dashboard/communication", tab: "calendar" },
  "/dashboard/calendar/view":                   { pathname: "/dashboard/communication", tab: "calendar" },
  "/dashboard/calendar/events":                 { pathname: "/dashboard/communication", tab: "calendar" },
  "/dashboard/calendar/new-event":              { pathname: "/dashboard/communication", tab: "calendar", drawer: "create" },
  "/dashboard/calendar/resources":              { pathname: "/dashboard/communication", tab: "calendar" },
  "/dashboard/calendar/bookings":               { pathname: "/dashboard/communication", tab: "calendar" },
  "/dashboard/calendar/availability":           { pathname: "/dashboard/communication", tab: "calendar" },
  "/dashboard/calendar/shifts":                 { pathname: "/dashboard/communication", tab: "calendar" },
  "/dashboard/calendar/reports":                { pathname: "/dashboard/communication", tab: "calendar" },
  "/dashboard/calendar/ai":                     { pathname: "/dashboard/communication", tab: "calendar" },
  "/dashboard/messages":                        { pathname: "/dashboard/communication", tab: "messages" },
  "/dashboard/email":                           { pathname: "/dashboard/communication", tab: "email" },
  "/dashboard/whatsapp":                        { pathname: "/dashboard/communication", tab: "whatsapp" },
  "/dashboard/calls":                           { pathname: "/dashboard/communication", tab: "calls" },
  "/dashboard/meetings":                        { pathname: "/dashboard/communication", tab: "meetings" },
  "/dashboard/notification-center":             { pathname: "/dashboard/communication", tab: "notifications" },
  "/dashboard/notification-center/list":        { pathname: "/dashboard/communication", tab: "notifications" },
  "/dashboard/notification-center/preferences": { pathname: "/dashboard/communication", tab: "notifications" },
  "/dashboard/notification-center/templates":   { pathname: "/dashboard/communication", tab: "notifications" },
  "/dashboard/notification-center/schedules":   { pathname: "/dashboard/communication", tab: "notifications" },
  "/dashboard/notification-center/reports":     { pathname: "/dashboard/communication", tab: "notifications" },
  "/dashboard/notification-center/ai":          { pathname: "/dashboard/communication", tab: "notifications" },

  // ── Analytics ─────────────────────────────────────────────────────────────
  "/dashboard/report-builder":                  { pathname: "/dashboard/analytics", tab: "report-builder" },
  "/dashboard/report-builder/executive":        { pathname: "/dashboard/analytics", tab: "report-builder" },
  "/dashboard/report-builder/catalog":          { pathname: "/dashboard/analytics", tab: "report-builder" },
  "/dashboard/report-builder/builder":          { pathname: "/dashboard/analytics", tab: "report-builder" },
  "/dashboard/report-builder/saved":            { pathname: "/dashboard/analytics", tab: "report-builder" },
  "/dashboard/report-builder/viewer":           { pathname: "/dashboard/analytics", tab: "report-builder" },
  "/dashboard/report-builder/dashboards":       { pathname: "/dashboard/analytics", tab: "report-builder" },
  "/dashboard/report-builder/schedules":        { pathname: "/dashboard/analytics", tab: "report-builder" },
  "/dashboard/report-builder/rls":              { pathname: "/dashboard/analytics", tab: "report-builder" },
  "/dashboard/report-builder/ai":               { pathname: "/dashboard/analytics", tab: "report-builder" },
  "/dashboard/reports":                         { pathname: "/dashboard/analytics", tab: "reports" },
  "/dashboard/reports/finance":                 { pathname: "/dashboard/analytics", tab: "reports" },
  "/dashboard/reports/inventory":               { pathname: "/dashboard/analytics", tab: "reports" },
  "/dashboard/reports/marketing":               { pathname: "/dashboard/analytics", tab: "reports" },
  "/dashboard/reports/payments":                { pathname: "/dashboard/analytics", tab: "reports" },
  "/dashboard/reports/procurement":             { pathname: "/dashboard/analytics", tab: "reports" },
  "/dashboard/reports/production":              { pathname: "/dashboard/analytics", tab: "reports" },
  "/dashboard/reports/sales":                   { pathname: "/dashboard/analytics", tab: "reports" },

  // ── Admin ─────────────────────────────────────────────────────────────────
  "/dashboard/permissions":                     { pathname: "/dashboard/admin", tab: "permissions" },
  "/dashboard/companies":                       { pathname: "/dashboard/admin", tab: "companies" },
  "/dashboard/security":                        { pathname: "/dashboard/admin", tab: "security" },
  "/dashboard/security/monitor":                { pathname: "/dashboard/admin", tab: "security" },
  "/dashboard/approvals":                       { pathname: "/dashboard/admin", tab: "approvals" },
  "/dashboard/custom-fields/fields":            { pathname: "/dashboard/admin", tab: "custom-fields" },
  "/dashboard/custom-fields/form-builder":      { pathname: "/dashboard/admin", tab: "custom-fields" },
  "/dashboard/custom-fields/workflow-rules":    { pathname: "/dashboard/admin", tab: "custom-fields" },
  "/dashboard/custom-fields/new-field":         { pathname: "/dashboard/admin", tab: "custom-fields", drawer: "create" },
  "/dashboard/custom-fields/values":            { pathname: "/dashboard/admin", tab: "custom-fields" },
  "/dashboard/custom-fields/reports":           { pathname: "/dashboard/admin", tab: "custom-fields" },
  "/dashboard/custom-fields/ai":                { pathname: "/dashboard/admin", tab: "custom-fields" },
  "/dashboard/utilities":                       { pathname: "/dashboard/admin", tab: "system-config" },
  "/dashboard/utilities/uom":                   { pathname: "/dashboard/admin", tab: "system-config" },
  "/dashboard/utilities/series":                { pathname: "/dashboard/admin", tab: "system-config" },
  "/dashboard/utilities/currencies":            { pathname: "/dashboard/admin", tab: "system-config" },
  "/dashboard/mobile":                          { pathname: "/dashboard/admin", tab: "mobile" },
  "/dashboard/mobile/approvals":                { pathname: "/dashboard/admin", tab: "mobile" },
  "/dashboard/mobile/devices":                  { pathname: "/dashboard/admin", tab: "mobile" },
  "/dashboard/logs":                            { pathname: "/dashboard/admin", tab: "logs" },
  "/dashboard/logs/compliance":                 { pathname: "/dashboard/admin", tab: "logs" },
  "/dashboard/logs/retention":                  { pathname: "/dashboard/admin", tab: "logs" },
  "/dashboard/import-history":                  { pathname: "/dashboard/admin", tab: "import-history" },

  // ── Integrations ───────────────────────────────────────────────────────────
  "/dashboard/webhooks":                        { pathname: "/dashboard/integrations", tab: "webhooks" },
  "/dashboard/webhooks/definitions":            { pathname: "/dashboard/integrations", tab: "webhooks" },
  "/dashboard/webhooks/subscriptions":          { pathname: "/dashboard/integrations", tab: "webhooks" },
  "/dashboard/webhooks/deliveries":             { pathname: "/dashboard/integrations", tab: "webhooks" },
  "/dashboard/webhooks/dead-letter":            { pathname: "/dashboard/integrations", tab: "webhooks" },
  "/dashboard/webhooks/inbound":                { pathname: "/dashboard/integrations", tab: "webhooks" },
  "/dashboard/webhooks/reports":                { pathname: "/dashboard/integrations", tab: "webhooks" },
  "/dashboard/developer":                       { pathname: "/dashboard/integrations", tab: "developer" },
  "/dashboard/developer/keys":                  { pathname: "/dashboard/integrations", tab: "developer" },
  "/dashboard/developer/graphql":               { pathname: "/dashboard/integrations", tab: "developer" },
};

/**
 * Resolve a redirect for a given pathname.
 * Returns null if no redirect applies.
 */
export function resolveRedirect(pathname: string): RedirectTarget | null {
  // Exact match
  if (EXACT_REDIRECTS[pathname]) return EXACT_REDIRECTS[pathname];

  // Prefix match for dynamic routes like /dashboard/traceability/recalls/[id]
  // Walk from longest to shortest prefix
  const parts = pathname.split("/");
  for (let i = parts.length - 1; i >= 2; i--) {
    const prefix = parts.slice(0, i).join("/");
    if (EXACT_REDIRECTS[prefix]) return EXACT_REDIRECTS[prefix];
  }

  return null;
}

/**
 * Build the redirect URL from a RedirectTarget.
 */
export function buildRedirectUrl(target: RedirectTarget): string {
  const params = new URLSearchParams();
  if (target.tab) params.set("tab", target.tab);
  if (target.subtab) params.set("subtab", target.subtab);
  if (target.drawer) params.set("drawer", target.drawer);
  const qs = params.toString();
  return qs ? `${target.pathname}?${qs}` : target.pathname;
}
